module.exports = function () {
  return [
    {
      '_id': 'Chelmsford 1',
      'against': '12',
      'division': 'prem',
      'draw': '2',
      'for': '21',
      'goal_difference': '9',
      'lose': '2',
      'played': '12',
      'points': '26',
      'win': '8'
    },
    {
      '_id': 'Canterbury 2',
      'against': '11',
      'division': 'prem',
      'draw': '2',
      'for': '16',
      'goal_difference': '5',
      'lose': '3',
      'played': '12',
      'points': '23',
      'win': '7'
    },
    {
      '_id': 'Brom & Becks 1',
      'against': '18',
      'division': 'prem',
      'draw': '1',
      'for': '42',
      'goal_difference': '24',
      'lose': '2',
      'played': '10',
      'points': '22',
      'win': '7'
    },
    {
      '_id': 'Broxbourne 1',
      'against': '11',
      'division': 'prem',
      'draw': '1',
      'for': '23',
      'goal_difference': '12',
      'lose': '3',
      'played': '11',
      'points': '22',
      'win': '7'
    },
    {
      '_id': 'CoP 1',
      'against': '18',
      'division': 'prem',
      'draw': '2',
      'for': '18',
      'goal_difference': '0',
      'lose': '4',
      'played': '12',
      'points': '20',
      'win': '6'
    },
    {
      '_id': 'Cambridge City 2',
      'against': '16',
      'division': 'prem',
      'draw': '4',
      'for': '20',
      'goal_difference': '4',
      'lose': '3',
      'played': '12',
      'points': '19',
      'win': '5'
    },
    {
      '_id': 'Wapping 1',
      'against': '16',
      'division': 'prem',
      'draw': '2',
      'for': '14',
      'goal_difference': '-2',
      'lose': '5',
      'played': '11',
      'points': '14',
      'win': '4'
    },
    {
      '_id': 'St Albans 2',
      'against': '28',
      'division': 'prem',
      'draw': '3',
      'for': '23',
      'goal_difference': '-5',
      'lose': '6',
      'played': '12',
      'points': '12',
      'win': '3'
    },
    {
      '_id': 'Harleston Magpies 2',
      'against': '25',
      'division': 'prem',
      'draw': '5',
      'for': '17',
      'goal_difference': '-8',
      'lose': '5',
      'played': '12',
      'points': '11',
      'win': '2'
    },
    {
      '_id': 'Norwich City 1',
      'against': '27',
      'division': 'prem',
      'draw': '1',
      'for': '10',
      'goal_difference': '-17',
      'lose': '7',
      'played': '11',
      'points': '10',
      'win': '3'
    },
    {
      '_id': 'West Herts 1',
      'against': '28',
      'division': 'prem',
      'draw': '3',
      'for': '19',
      'goal_difference': '-9',
      'lose': '6',
      'played': '11',
      'points': '9',
      'win': '2'
    },
    {
      '_id': 'Sevenoaks 2',
      'against': '23',
      'division': 'prem',
      'draw': '2',
      'for': '10',
      'goal_difference': '-13',
      'lose': '9',
      'played': '12',
      'points': '5',
      'win': '1'
    },
    {
      '_id': 'East London 1',
      'against': '9',
      'division': '1s',
      'draw': '2',
      'for': '44',
      'goal_difference': '35',
      'lose': '1',
      'played': '12',
      'points': '29',
      'win': '9'
    },
    {
      '_id': 'Maidstone 1',
      'against': '21',
      'division': '1s',
      'draw': '1',
      'for': '55',
      'goal_difference': '34',
      'lose': '2',
      'played': '12',
      'points': '28',
      'win': '9'
    },
    {
      '_id': 'Upminster 1',
      'against': '7',
      'division': '1s',
      'draw': '1',
      'for': '29',
      'goal_difference': '22',
      'lose': '1',
      'played': '11',
      'points': '28',
      'win': '9'
    },
    {
      '_id': 'Blueharts 1',
      'against': '18',
      'division': '1s',
      'draw': '3',
      'for': '31',
      'goal_difference': '13',
      'lose': '1',
      'played': '11',
      'points': '24',
      'win': '7'
    },
    {
      '_id': 'Chelmsford 2',
      'against': '22',
      'division': '1s',
      'draw': '2',
      'for': '17',
      'goal_difference': '-5',
      'lose': '4',
      'played': '11',
      'points': '17',
      'win': '5'
    },
    {
      '_id': 'Bishops Stortford 1',
      'against': '19',
      'division': '1s',
      'draw': '3',
      'for': '24',
      'goal_difference': '5',
      'lose': '4',
      'played': '11',
      'points': '15',
      'win': '4'
    },
    {
      '_id': 'Crostyx 1',
      'against': '16',
      'division': '1s',
      'draw': '3',
      'for': '10',
      'goal_difference': '-6',
      'lose': '4',
      'played': '11',
      'points': '15',
      'win': '4'
    },
    {
      '_id': 'Old Loughts 1',
      'against': '19',
      'division': '1s',
      'draw': '3',
      'for': '16',
      'goal_difference': '-3',
      'lose': '5',
      'played': '11',
      'points': '12',
      'win': '3'
    },
    {
      '_id': 'Tunbridge Wells 1',
      'against': '35',
      'division': '1s',
      'draw': '2',
      'for': '11',
      'goal_difference': '-24',
      'lose': '8',
      'played': '12',
      'points': '8',
      'win': '2'
    },
    {
      '_id': 'Ashford 1',
      'against': '41',
      'division': '1s',
      'draw': '1',
      'for': '15',
      'goal_difference': '-26',
      'lose': '9',
      'played': '12',
      'points': '7',
      'win': '2'
    },
    {
      '_id': 'Colchester 1',
      'against': '37',
      'division': '1s',
      'draw': '0',
      'for': '16',
      'goal_difference': '-21',
      'lose': '10',
      'played': '12',
      'points': '6',
      'win': '2'
    },
    {
      '_id': 'Canterbury 2A',
      'against': '34',
      'division': '1s',
      'draw': '3',
      'for': '10',
      'goal_difference': '-24',
      'lose': '7',
      'played': '10',
      'points': '3',
      'win': '0'
    },
    {
      '_id': 'North Norfolk 1',
      'against': '12',
      'division': '2ne',
      'draw': '1',
      'for': '45',
      'goal_difference': '33',
      'lose': '1',
      'played': '12',
      'points': '31',
      'win': '10'
    },
    {
      '_id': 'Watton 1',
      'against': '13',
      'division': '2ne',
      'draw': '1',
      'for': '43',
      'goal_difference': '30',
      'lose': '1',
      'played': '12',
      'points': '31',
      'win': '10'
    },
    {
      '_id': 'Bury St Edmunds 1',
      'against': '13',
      'division': '2ne',
      'draw': '0',
      'for': '36',
      'goal_difference': '23',
      'lose': '3',
      'played': '12',
      'points': '27',
      'win': '9'
    },
    {
      '_id': 'Norwich Dragons 2',
      'against': '15',
      'division': '2ne',
      'draw': '0',
      'for': '32',
      'goal_difference': '17',
      'lose': '3',
      'played': '12',
      'points': '27',
      'win': '9'
    },
    {
      '_id': 'Harleston Magpies 3',
      'against': '20',
      'division': '2ne',
      'draw': '3',
      'for': '23',
      'goal_difference': '3',
      'lose': '4',
      'played': '12',
      'points': '18',
      'win': '5'
    },
    {
      '_id': 'UEA Women 1',
      'against': '36',
      'division': '2ne',
      'draw': '2',
      'for': '41',
      'goal_difference': '5',
      'lose': '5',
      'played': '12',
      'points': '17',
      'win': '5'
    },
    {
      '_id': 'Norwich City 2',
      'against': '15',
      'division': '2ne',
      'draw': '0',
      'for': '20',
      'goal_difference': '5',
      'lose': '7',
      'played': '12',
      'points': '15',
      'win': '5'
    },
    {
      '_id': 'Norwich Dragons 3',
      'against': '41',
      'division': '2ne',
      'draw': '0',
      'for': '19',
      'goal_difference': '-22',
      'lose': '7',
      'played': '12',
      'points': '15',
      'win': '5'
    },
    {
      '_id': 'Christchurch 1',
      'against': '24',
      'division': '2ne',
      'draw': '2',
      'for': '20',
      'goal_difference': '-4',
      'lose': '6',
      'played': '12',
      'points': '14',
      'win': '4'
    },
    {
      '_id': 'Yarmouth 1',
      'against': '27',
      'division': '2ne',
      'draw': '2',
      'for': '20',
      'goal_difference': '-7',
      'lose': '7',
      'played': '12',
      'points': '11',
      'win': '3'
    },
    {
      '_id': 'Dereham 2',
      'against': '24',
      'division': '2ne',
      'draw': '1',
      'for': '8',
      'goal_difference': '-16',
      'lose': '10',
      'played': '12',
      'points': '4',
      'win': '1'
    },
    {
      '_id': 'Felixstowe 1',
      'against': '68',
      'division': '2ne',
      'draw': '0',
      'for': '1',
      'goal_difference': '-67',
      'lose': '12',
      'played': '12',
      'points': '0',
      'win': '0'
    },
    {
      '_id': 'CoP 2',
      'against': '5',
      'division': '2nw',
      'draw': '1',
      'for': '53',
      'goal_difference': '48',
      'lose': '0',
      'played': '12',
      'points': '34',
      'win': '11'
    },
    {
      '_id': 'St Ives 1',
      'against': '16',
      'division': '2nw',
      'draw': '3',
      'for': '27',
      'goal_difference': '11',
      'lose': '2',
      'played': '12',
      'points': '24',
      'win': '7'
    },
    {
      '_id': 'Cambridge Nomads 1',
      'against': '15',
      'division': '2nw',
      'draw': '2',
      'for': '27',
      'goal_difference': '12',
      'lose': '3',
      'played': '12',
      'points': '23',
      'win': '7'
    },
    {
      '_id': 'Cambridge South 1',
      'against': '22',
      'division': '2nw',
      'draw': '2',
      'for': '28',
      'goal_difference': '6',
      'lose': '4',
      'played': '12',
      'points': '20',
      'win': '6'
    },
    {
      '_id': 'Cambridge City 4',
      'against': '19',
      'division': '2nw',
      'draw': '2',
      'for': '20',
      'goal_difference': '1',
      'lose': '5',
      'played': '12',
      'points': '17',
      'win': '5'
    },
    {
      '_id': 'Bourne Deeping 1',
      'against': '21',
      'division': '2nw',
      'draw': '2',
      'for': '21',
      'goal_difference': '0',
      'lose': '5',
      'played': '12',
      'points': '17',
      'win': '5'
    },
    {
      '_id': 'Pelicans 1',
      'against': '21',
      'division': '2nw',
      'draw': '1',
      'for': '36',
      'goal_difference': '15',
      'lose': '6',
      'played': '12',
      'points': '16',
      'win': '5'
    },
    {
      '_id': 'St Ives 2',
      'against': '37',
      'division': '2nw',
      'draw': '0',
      'for': '24',
      'goal_difference': '-13',
      'lose': '7',
      'played': '12',
      'points': '15',
      'win': '5'
    },
    {
      '_id': 'Spalding 1',
      'against': '28',
      'division': '2nw',
      'draw': '2',
      'for': '15',
      'goal_difference': '-13',
      'lose': '6',
      'played': '12',
      'points': '14',
      'win': '4'
    },
    {
      '_id': 'Long Sutton 1',
      'against': '29',
      'division': '2nw',
      'draw': '1',
      'for': '20',
      'goal_difference': '-9',
      'lose': '8',
      'played': '12',
      'points': '10',
      'win': '3'
    },
    {
      '_id': 'Alford & District 1',
      'against': '45',
      'division': '2nw',
      'draw': '0',
      'for': '18',
      'goal_difference': '-27',
      'lose': '9',
      'played': '12',
      'points': '9',
      'win': '3'
    },
    {
      '_id': 'Newmarket 1',
      'against': '38',
      'division': '2nw',
      'draw': '0',
      'for': '7',
      'goal_difference': '-31',
      'lose': '9',
      'played': '12',
      'points': '9',
      'win': '3'
    },
    {
      '_id': 'Basildon 1',
      'against': '11',
      'division': '2se',
      'draw': '1',
      'for': '32',
      'goal_difference': '21',
      'lose': '1',
      'played': '11',
      'points': '28',
      'win': '9'
    },
    {
      '_id': 'Burnt Ash 1',
      'against': '11',
      'division': '2se',
      'draw': '0',
      'for': '36',
      'goal_difference': '25',
      'lose': '2',
      'played': '11',
      'points': '27',
      'win': '9'
    },
    {
      '_id': 'Folkestone 1',
      'against': '14',
      'division': '2se',
      'draw': '1',
      'for': '29',
      'goal_difference': '15',
      'lose': '3',
      'played': '11',
      'points': '22',
      'win': '7'
    },
    {
      '_id': 'Holcombe 1A',
      'against': '10',
      'division': '2se',
      'draw': '2',
      'for': '21',
      'goal_difference': '11',
      'lose': '2',
      'played': '10',
      'points': '20',
      'win': '6'
    },
    {
      '_id': 'Kings and Alleyns 1',
      'against': '18',
      'division': '2se',
      'draw': '1',
      'for': '24',
      'goal_difference': '6',
      'lose': '5',
      'played': '11',
      'points': '16',
      'win': '5'
    },
    {
      '_id': 'Brom & Becks 2',
      'against': '26',
      'division': '2se',
      'draw': '1',
      'for': '23',
      'goal_difference': '-3',
      'lose': '5',
      'played': '11',
      'points': '16',
      'win': '5'
    },
    {
      '_id': 'Sevenoaks 3',
      'against': '13',
      'division': '2se',
      'draw': '2',
      'for': '23',
      'goal_difference': '10',
      'lose': '5',
      'played': '11',
      'points': '14',
      'win': '4'
    },
    {
      '_id': 'Southend 1',
      'against': '21',
      'division': '2se',
      'draw': '1',
      'for': '22',
      'goal_difference': '1',
      'lose': '6',
      'played': '11',
      'points': '13',
      'win': '4'
    },
    {
      '_id': 'Havering 1',
      'against': '44',
      'division': '2se',
      'draw': '2',
      'for': '26',
      'goal_difference': '-18',
      'lose': '7',
      'played': '11',
      'points': '8',
      'win': '2'
    },
    {
      '_id': 'Southend & Benfleet 1',
      'against': '33',
      'division': '2se',
      'draw': '3',
      'for': '17',
      'goal_difference': '-16',
      'lose': '7',
      'played': '11',
      'points': '6',
      'win': '1'
    },
    {
      '_id': 'Redbridge & Ilford 1',
      'against': '60',
      'division': '2se',
      'draw': '0',
      'for': '8',
      'goal_difference': '-52',
      'lose': '10',
      'played': '11',
      'points': '3',
      'win': '1'
    },
    {
      '_id': 'Tunbridge Wells 2',
      'against': '',
      'division': '2se',
      'draw': '0',
      'for': '',
      'goal_difference': '',
      'lose': '0',
      'played': '0',
      'points': '0',
      'win': '0'
    },
    {
      '_id': 'Letchworth 1',
      'against': '14',
      'division': '2sw',
      'draw': '3',
      'for': '38',
      'goal_difference': '24',
      'lose': '0',
      'played': '11',
      'points': '27',
      'win': '8'
    },
    {
      '_id': 'Wapping 2',
      'against': '6',
      'division': '2sw',
      'draw': '2',
      'for': '22',
      'goal_difference': '16',
      'lose': '2',
      'played': '11',
      'points': '23',
      'win': '7'
    },
    {
      '_id': 'Waltham Forest 1',
      'against': '20',
      'division': '2sw',
      'draw': '2',
      'for': '31',
      'goal_difference': '11',
      'lose': '3',
      'played': '11',
      'points': '20',
      'win': '6'
    },
    {
      '_id': 'St Albans 3',
      'against': '19',
      'division': '2sw',
      'draw': '5',
      'for': '25',
      'goal_difference': '6',
      'lose': '2',
      'played': '11',
      'points': '17',
      'win': '4'
    },
    {
      '_id': 'Brentwood 1',
      'against': '11',
      'division': '2sw',
      'draw': '4',
      'for': '14',
      'goal_difference': '3',
      'lose': '2',
      'played': '10',
      'points': '16',
      'win': '4'
    },
    {
      '_id': 'East London 2',
      'against': '21',
      'division': '2sw',
      'draw': '4',
      'for': '23',
      'goal_difference': '2',
      'lose': '3',
      'played': '11',
      'points': '16',
      'win': '4'
    },
    {
      '_id': 'Stevenage 1',
      'against': '20',
      'division': '2sw',
      'draw': '2',
      'for': '25',
      'goal_difference': '5',
      'lose': '5',
      'played': '11',
      'points': '14',
      'win': '4'
    },
    {
      '_id': 'Shefford & Sandy 1',
      'against': '27',
      'division': '2sw',
      'draw': '1',
      'for': '18',
      'goal_difference': '-9',
      'lose': '6',
      'played': '11',
      'points': '13',
      'win': '4'
    },
    {
      '_id': 'Leighton Buzzard 1',
      'against': '34',
      'division': '2sw',
      'draw': '2',
      'for': '13',
      'goal_difference': '-21',
      'lose': '7',
      'played': '11',
      'points': '8',
      'win': '2'
    },
    {
      '_id': 'West Herts 2',
      'against': '26',
      'division': '2sw',
      'draw': '4',
      'for': '14',
      'goal_difference': '-12',
      'lose': '6',
      'played': '11',
      'points': '7',
      'win': '1'
    },
    {
      '_id': 'Harpenden 1',
      'against': '34',
      'division': '2sw',
      'draw': '3',
      'for': '9',
      'goal_difference': '-25',
      'lose': '8',
      'played': '11',
      'points': '3',
      'win': '0'
    },
    {
      '_id': 'Old Loughts 2',
      'against': '',
      'division': '2sw',
      'draw': '0',
      'for': '',
      'goal_difference': '',
      'lose': '0',
      'played': '0',
      'points': '0',
      'win': '0'
    },
    {
      '_id': 'Ely City 2',
      'against': '9',
      'division': '5nw(s)',
      'draw': '0',
      'for': '70',
      'goal_difference': '61',
      'lose': '0',
      'played': '10',
      'points': '30',
      'win': '10'
    },
    {
      '_id': 'Cambridge City 6',
      'against': '10',
      'division': '5nw(s)',
      'draw': '0',
      'for': '52',
      'goal_difference': '42',
      'lose': '2',
      'played': '11',
      'points': '27',
      'win': '9'
    },
    {
      '_id': 'St Ives 4',
      'against': '11',
      'division': '5nw(s)',
      'draw': '1',
      'for': '36',
      'goal_difference': '25',
      'lose': '2',
      'played': '11',
      'points': '25',
      'win': '8'
    },
    {
      '_id': 'Newmarket 3',
      'against': '16',
      'division': '5nw(s)',
      'draw': '1',
      'for': '19',
      'goal_difference': '3',
      'lose': '3',
      'played': '11',
      'points': '22',
      'win': '7'
    },
    {
      '_id': 'Bury St Edmunds 4',
      'against': '37',
      'division': '5nw(s)',
      'draw': '2',
      'for': '45',
      'goal_difference': '8',
      'lose': '4',
      'played': '11',
      'points': '17',
      'win': '5'
    },
    {
      '_id': 'Cambridge South 4',
      'against': '34',
      'division': '5nw(s)',
      'draw': '0',
      'for': '18',
      'goal_difference': '-16',
      'lose': '7',
      'played': '11',
      'points': '12',
      'win': '4'
    },
    {
      '_id': 'Sudbury 3',
      'against': '29',
      'division': '5nw(s)',
      'draw': '1',
      'for': '34',
      'goal_difference': '5',
      'lose': '5',
      'played': '11',
      'points': '10',
      'win': '5'
    },
    {
      '_id': 'Wisbech Town 3',
      'against': '40',
      'division': '5nw(s)',
      'draw': '0',
      'for': '10',
      'goal_difference': '-30',
      'lose': '8',
      'played': '11',
      'points': '9',
      'win': '3'
    },
    {
      '_id': 'Huntingdon 2',
      'against': '33',
      'division': '5nw(s)',
      'draw': '1',
      'for': '19',
      'goal_difference': '-14',
      'lose': '7',
      'played': '11',
      'points': '7',
      'win': '3'
    },
    {
      '_id': 'Ely City 3',
      'against': '42',
      'division': '5nw(s)',
      'draw': '0',
      'for': '7',
      'goal_difference': '-35',
      'lose': '10',
      'played': '11',
      'points': '3',
      'win': '1'
    },
    {
      '_id': 'Newmarket 4',
      'against': '60',
      'division': '5nw(s)',
      'draw': '0',
      'for': '11',
      'goal_difference': '-49',
      'lose': '9',
      'played': '11',
      'points': '3',
      'win': '2'
    }
  ]
}
