module.exports = function () {
    return {
        '10se': {
            'Braintree 5': {
                'against': '4',
                'draw': '1',
                'for': '22',
                'goal_difference': '18',
                'lose': '0',
                'played': '5',
                'points': '13',
                'win': '4',
            },
            'Chelmsford 7': {
                'against': '3',
                'draw': '2',
                'for': '10',
                'goal_difference': '7',
                'lose': '1',
                'played': '5',
                'points': '8',
                'win': '2',
            },
            'East London 9': {
                'against': '10',
                'draw': '1',
                'for': '9',
                'goal_difference': '-1',
                'lose': '2',
                'played': '5',
                'points': '7',
                'win': '2',
            },
            'Old Loughts Willows 2': {
                'against': '4',
                'draw': '2',
                'for': '7',
                'goal_difference': '3',
                'lose': '1',
                'played': '5',
                'points': '8',
                'win': '2',
            },
            'Old Southendian 6': {
                'against': '11',
                'draw': '0',
                'for': '14',
                'goal_difference': '3',
                'lose': '2',
                'played': '5',
                'points': '9',
                'win': '3',
            },
            'Romford 3': {
                'against': '15',
                'draw': '0',
                'for': '13',
                'goal_difference': '-2',
                'lose': '3',
                'played': '5',
                'points': '6',
                'win': '2',
            },
            'Saffron Walden 8': {
                'against': '17',
                'draw': '0',
                'for': '7',
                'goal_difference': '-10',
                'lose': '4',
                'played': '5',
                'points': '3',
                'win': '1',
            },
            'Waltham Forest 5': {
                'against': '19',
                'draw': '2',
                'for': '1',
                'goal_difference': '-18',
                'lose': '3',
                'played': '5',
                'points': '2',
                'win': '0',
            }
        },
        '3se': {
            'Braintree 1': {
                'against': '9',
                'draw': '1',
                'for': '13',
                'goal_difference': '4',
                'lose': '1',
                'played': '5',
                'points': '10',
                'win': '3',
            },
            'Brentwood 1': {
                'against': '5',
                'draw': '0',
                'for': '26',
                'goal_difference': '21',
                'lose': '0',
                'played': '5',
                'points': '15',
                'win': '5',
            },
            'Brentwood 2': {
                'against': '24',
                'draw': '0',
                'for': '10',
                'goal_difference': '-14',
                'lose': '4',
                'played': '5',
                'points': '3',
                'win': '1',
            },
            'Clacton 1': {
                'against': '16',
                'draw': '1',
                'for': '9',
                'goal_difference': '-7',
                'lose': '3',
                'played': '5',
                'points': '4',
                'win': '1',
            },
            'Crostyx 2': {
                'against': '20',
                'draw': '0',
                'for': '6',
                'goal_difference': '-14',
                'lose': '4',
                'played': '5',
                'points': '3',
                'win': '1',
            },
            'East London 3': {
                'against': '17',
                'draw': '0',
                'for': '10',
                'goal_difference': '-7',
                'lose': '4',
                'played': '5',
                'points': '3',
                'win': '1',
            },
            'Maldon 1': {
                'against': '18',
                'draw': '0',
                'for': '12',
                'goal_difference': '-6',
                'lose': '3',
                'played': '5',
                'points': '6',
                'win': '2',
            },
            'Redbridge &Ilford 1': {
                'against': '8',
                'draw': '0',
                'for': '14',
                'goal_difference': '6',
                'lose': '2',
                'played': '5',
                'points': '9',
                'win': '3',
            },
            'Southend 1': {
                'against': '11',
                'draw': '3',
                'for': '13',
                'goal_difference': '2',
                'lose': '1',
                'played': '5',
                'points': '6',
                'win': '1',
            },
            'Upminster 2': {
                'against': '11',
                'draw': '2',
                'for': '11',
                'goal_difference': '0',
                'lose': '1',
                'played': '5',
                'points': '8',
                'win': '2',
            },
            'Wapping 5': {
                'against': '6',
                'draw': '1',
                'for': '22',
                'goal_difference': '16',
                'lose': '0',
                'played': '5',
                'points': '13',
                'win': '4',
            },
            'Wapping 6': {
                'against': '11',
                'draw': '2',
                'for': '10',
                'goal_difference': '-1',
                'lose': '2',
                'played': '5',
                'points': '5',
                'win': '1',
            }
        },
        '4se': {
            'Brentwood 3': {
                'against': '24',
                'draw': '1',
                'for': '4',
                'goal_difference': '-20',
                'lose': '4',
                'played': '5',
                'points': '1',
                'win': '0',
            },
            'Chelmsford 3': {
                'against': '6',
                'draw': '0',
                'for': '15',
                'goal_difference': '9',
                'lose': '1',
                'played': '5',
                'points': '12',
                'win': '4',
            },
            'Colchester 2': {
                'against': '19',
                'draw': '0',
                'for': '5',
                'goal_difference': '-14',
                'lose': '5',
                'played': '5',
                'points': '0',
                'win': '0',
            },
            'East London 4': {
                'against': '10',
                'draw': '0',
                'for': '8',
                'goal_difference': '-2',
                'lose': '3',
                'played': '5',
                'points': '6',
                'win': '2',
            },
            'Havering 2': {
                'against': '20',
                'draw': '0',
                'for': '7',
                'goal_difference': '-13',
                'lose': '4',
                'played': '5',
                'points': '3',
                'win': '1',
            },
            'Old Southendian 2': {
                'against': '22',
                'draw': '0',
                'for': '10',
                'goal_difference': '-12',
                'lose': '3',
                'played': '5',
                'points': '6',
                'win': '2',
            },
            'Plashet 1': {
                'against': '6',
                'draw': '0',
                'for': '29',
                'goal_difference': '23',
                'lose': '1',
                'played': '5',
                'points': '12',
                'win': '4',
            },
            'Romford 1': {
                'against': '19',
                'draw': '1',
                'for': '13',
                'goal_difference': '-6',
                'lose': '3',
                'played': '5',
                'points': '4',
                'win': '1',
            },
            'Saffron Walden 3': {
                'against': '11',
                'draw': '0',
                'for': '29',
                'goal_difference': '18',
                'lose': '0',
                'played': '5',
                'points': '15',
                'win': '5',
            },
            'Waltham Forest 2': {
                'against': '8',
                'draw': '0',
                'for': '17',
                'goal_difference': '9',
                'lose': '1',
                'played': '5',
                'points': '12',
                'win': '4',
            },
            'Wapping 7': {
                'against': '7',
                'draw': '0',
                'for': '11',
                'goal_difference': '4',
                'lose': '2',
                'played': '5',
                'points': '9',
                'win': '3',
            },
            'Witham 2': {
                'against': '9',
                'draw': '2',
                'for': '13',
                'goal_difference': '4',
                'lose': '1',
                'played': '5',
                'points': '8',
                'win': '2',
            }
        },
        '5se': {
            'Clacton 2': {
                'against': '16',
                'draw': '0',
                'for': '2',
                'goal_difference': '-14',
                'lose': '5',
                'played': '5',
                'points': '0',
                'win': '0',
            },
            'Crostyx 3': {
                'against': '7',
                'draw': '1',
                'for': '10',
                'goal_difference': '3',
                'lose': '2',
                'played': '5',
                'points': '7',
                'win': '2',
            },
            'East London 5': {
                'against': '14',
                'draw': '0',
                'for': '9',
                'goal_difference': '-5',
                'lose': '3',
                'played': '5',
                'points': '6',
                'win': '2',
            },
            'Old Southendian 3': {
                'against': '11',
                'draw': '2',
                'for': '8',
                'goal_difference': '-3',
                'lose': '2',
                'played': '5',
                'points': '5',
                'win': '1',
            },
            'Redbridge &Ilford 2': {
                'against': '13',
                'draw': '1',
                'for': '15',
                'goal_difference': '2',
                'lose': '2',
                'played': '5',
                'points': '7',
                'win': '2',
            },
            'Rochford 1': {
                'against': '9',
                'draw': '0',
                'for': '19',
                'goal_difference': '10',
                'lose': '1',
                'played': '5',
                'points': '12',
                'win': '4',
            },
            'Southend 2': {
                'against': '15',
                'draw': '2',
                'for': '11',
                'goal_difference': '-4',
                'lose': '2',
                'played': '5',
                'points': '5',
                'win': '1',
            },
            'Thurrock 1': {
                'against': '5',
                'draw': '0',
                'for': '19',
                'goal_difference': '14',
                'lose': '0',
                'played': '5',
                'points': '15',
                'win': '5',
            },
            'Upminster 3': {
                'against': '8',
                'draw': '2',
                'for': '10',
                'goal_difference': '2',
                'lose': '1',
                'played': '5',
                'points': '8',
                'win': '2',
            },
            'Waltham Forest 3': {
                'against': '13',
                'draw': '1',
                'for': '13',
                'goal_difference': '0',
                'lose': '2',
                'played': '5',
                'points': '7',
                'win': '2',
            },
            'Wapping 8': {
                'against': '9',
                'draw': '1',
                'for': '10',
                'goal_difference': '1',
                'lose': '2',
                'played': '5',
                'points': '7',
                'win': '2',
            },
            'Witham 3': {
                'against': '14',
                'draw': '0',
                'for': '8',
                'goal_difference': '-6',
                'lose': '3',
                'played': '5',
                'points': '6',
                'win': '2',
            }
        },
        '6se': {
            'Basildon 1': {
                'against': '27',
                'draw': '0',
                'for': '5',
                'goal_difference': '-22',
                'lose': '4',
                'played': '5',
                'points': '3',
                'win': '1',
            },
            'Braintree 2': {
                'against': '10',
                'draw': '1',
                'for': '8',
                'goal_difference': '-2',
                'lose': '2',
                'played': '5',
                'points': '7',
                'win': '2',
            },
            'Brentwood 4': {
                'against': '24',
                'draw': '1',
                'for': '9',
                'goal_difference': '-15',
                'lose': '3',
                'played': '5',
                'points': '4',
                'win': '1',
            },
            'Chelmsford 4': {
                'against': '11',
                'draw': '1',
                'for': '23',
                'goal_difference': '12',
                'lose': '1',
                'played': '5',
                'points': '10',
                'win': '3',
            },
            'Chelmsford 5': {
                'against': '13',
                'draw': '0',
                'for': '14',
                'goal_difference': '1',
                'lose': '3',
                'played': '5',
                'points': '6',
                'win': '2',
            },
            'Colchester 3': {
                'against': '14',
                'draw': '2',
                'for': '13',
                'goal_difference': '-1',
                'lose': '2',
                'played': '5',
                'points': '5',
                'win': '1',
            },
            'East London 6': {
                'against': '7',
                'draw': '1',
                'for': '15',
                'goal_difference': '8',
                'lose': '2',
                'played': '5',
                'points': '7',
                'win': '2',
            },
            'East London 7': {
                'against': '8',
                'draw': '0',
                'for': '17',
                'goal_difference': '9',
                'lose': '2',
                'played': '5',
                'points': '9',
                'win': '3',
            },
            'Maldon 2': {
                'against': '23',
                'draw': '1',
                'for': '11',
                'goal_difference': '-12',
                'lose': '3',
                'played': '5',
                'points': '4',
                'win': '1',
            },
            'Old Loughts Academy': {
                'against': '7',
                'draw': '0',
                'for': '27',
                'goal_difference': '20',
                'lose': '0',
                'played': '5',
                'points': '15',
                'win': '5',
            },
            'Saffron Walden 4': {
                'against': '8',
                'draw': '1',
                'for': '16',
                'goal_difference': '8',
                'lose': '1',
                'played': '5',
                'points': '10',
                'win': '3',
            },
            'Wapping 9': {
                'against': '16',
                'draw': '0',
                'for': '10',
                'goal_difference': '-6',
                'lose': '3',
                'played': '5',
                'points': '6',
                'win': '2',
            }
        },
        '7se': {
            'Braintree 3': {
                'against': '22',
                'draw': '0',
                'for': '15',
                'goal_difference': '-7',
                'lose': '4',
                'played': '5',
                'points': '3',
                'win': '1',
            },
            'Chelmsford 6': {
                'against': '8',
                'draw': '1',
                'for': '14',
                'goal_difference': '6',
                'lose': '2',
                'played': '5',
                'points': '7',
                'win': '2',
            },
            'Havering 3': {
                'against': '6',
                'draw': '1',
                'for': '27',
                'goal_difference': '21',
                'lose': '1',
                'played': '5',
                'points': '10',
                'win': '3',
            },
            'Old Loughts Loppers': {
                'against': '7',
                'draw': '1',
                'for': '24',
                'goal_difference': '17',
                'lose': '0',
                'played': '5',
                'points': '13',
                'win': '4',
            },
            'Redbridge &Ilford 3': {
                'against': '8',
                'draw': '1',
                'for': '7',
                'goal_difference': '-1',
                'lose': '2',
                'played': '4',
                'points': '4',
                'win': '1',
            },
            'Saffron Walden 5': {
                'against': '7',
                'draw': '0',
                'for': '21',
                'goal_difference': '14',
                'lose': '0',
                'played': '5',
                'points': '15',
                'win': '5',
            },
            'Saffron Walden 6': {
                'against': '8',
                'draw': '1',
                'for': '10',
                'goal_difference': '2',
                'lose': '1',
                'played': '4',
                'points': '7',
                'win': '2',
            },
            'Upminster 4': {
                'against': '8',
                'draw': '1',
                'for': '14',
                'goal_difference': '6',
                'lose': '1',
                'played': '5',
                'points': '10',
                'win': '3',
            },
            'Waltham Forest 4': {
                'against': '35',
                'draw': '0',
                'for': '4',
                'goal_difference': '-31',
                'lose': '5',
                'played': '5',
                'points': '0',
                'win': '0',
            },
            'Wapping X': {
                'against': '19',
                'draw': '1',
                'for': '7',
                'goal_difference': '-12',
                'lose': '4',
                'played': '5',
                'points': '1',
                'win': '0',
            },
            'Witham 4': {
                'against': '18',
                'draw': '0',
                'for': '11',
                'goal_difference': '-7',
                'lose': '3',
                'played': '5',
                'points': '6',
                'win': '2',
            },
            'Witham Academy': {
                'against': '19',
                'draw': '1',
                'for': '11',
                'goal_difference': '-8',
                'lose': '2',
                'played': '5',
                'points': '7',
                'win': '2',
            }
        },
        '8se': {
            'Braintree Knights': {
                'against': '14',
                'draw': '1',
                'for': '15',
                'goal_difference': '1',
                'lose': '2',
                'played': '5',
                'points': '7',
                'win': '2',
            },
            'Brentwood 5': {
                'against': '23',
                'draw': '1',
                'for': '8',
                'goal_difference': '-15',
                'lose': '4',
                'played': '5',
                'points': '1',
                'win': '0',
            },
            'Brentwood Academy': {
                'against': '14',
                'draw': '1',
                'for': '8',
                'goal_difference': '-6',
                'lose': '2',
                'played': '5',
                'points': '7',
                'win': '2',
            },
            'Colchester 4': {
                'against': '14',
                'draw': '0',
                'for': '7',
                'goal_difference': '-7',
                'lose': '3',
                'played': '4',
                'points': '3',
                'win': '1',
            },
            'East London 8': {
                'against': '5',
                'draw': '0',
                'for': '10',
                'goal_difference': '5',
                'lose': '3',
                'played': '5',
                'points': '6',
                'win': '2',
            },
            'Old Southendian 4': {
                'against': '6',
                'draw': '1',
                'for': '8',
                'goal_difference': '2',
                'lose': '1',
                'played': '4',
                'points': '7',
                'win': '2',
            },
            'Old Southendian 5': {
                'against': '9',
                'draw': '0',
                'for': '5',
                'goal_difference': '-4',
                'lose': '2',
                'played': '4',
                'points': '3',
                'win': '2',
            },
            'Romford 2': {
                'against': '7',
                'draw': '0',
                'for': '17',
                'goal_difference': '10',
                'lose': '1',
                'played': '5',
                'points': '12',
                'win': '4',
            },
            'Saffron Walden 7': {
                'against': '16',
                'draw': '2',
                'for': '9',
                'goal_difference': '-7',
                'lose': '2',
                'played': '5',
                'points': '5',
                'win': '1',
            },
            'Thurrock 2': {
                'against': '27',
                'draw': '0',
                'for': '8',
                'goal_difference': '-19',
                'lose': '4',
                'played': '5',
                'points': '3',
                'win': '1',
            },
            'Tower Hamlets 1': {
                'against': '2',
                'draw': '0',
                'for': '34',
                'goal_difference': '32',
                'lose': '0',
                'played': '5',
                'points': '15',
                'win': '5',
            },
            'Wapping XI': {
                'against': '6',
                'draw': '0',
                'for': '14',
                'goal_difference': '8',
                'lose': '1',
                'played': '4',
                'points': '9',
                'win': '3',
            }
        },
        '9se': {
            'Crostyx 4': {
                'against': '13',
                'draw': '0',
                'for': '15',
                'goal_difference': '2',
                'lose': '2',
                'played': '5',
                'points': '9',
                'win': '3',
            },
            'Havering 4': {
                'against': '10',
                'draw': '2',
                'for': '8',
                'goal_difference': '-2',
                'lose': '2',
                'played': '5',
                'points': '5',
                'win': '1',
            },
            'London Royals 1': {
                'against': '13',
                'draw': '0',
                'for': '9',
                'goal_difference': '-4',
                'lose': '4',
                'played': '5',
                'points': '3',
                'win': '1',
            },
            'Maldon Academy': {
                'against': '15',
                'draw': '1',
                'for': '6',
                'goal_difference': '-9',
                'lose': '3',
                'played': '5',
                'points': '4',
                'win': '1',
            },
            'Old Loughts Willows 1': {
                'against': '4',
                'draw': '1',
                'for': '27',
                'goal_difference': '23',
                'lose': '0',
                'played': '5',
                'points': '13',
                'win': '4',
            },
            'Rochford 2': {
                'against': '16',
                'draw': '1',
                'for': '7',
                'goal_difference': '-9',
                'lose': '3',
                'played': '5',
                'points': '4',
                'win': '1',
            },
            'Southend 3': {
                'against': '14',
                'draw': '1',
                'for': '14',
                'goal_difference': '0',
                'lose': '1',
                'played': '5',
                'points': '10',
                'win': '3',
            },
            'Upminster 5': {
                'against': '16',
                'draw': '0',
                'for': '15',
                'goal_difference': '-1',
                'lose': '2',
                'played': '5',
                'points': '9',
                'win': '3',
            }
        }
    }
};