module.exports = function () {
  return [
    {
      '_id': 'F:Chelmsford 1',
      'against': '12',
      'division': 'prem',
      'draw': '2',
      'for': '21',
      'gender': 'F',
      'goal_difference': '9',
      'lose': '2',
      'played': '12',
      'points': '26',
      'team': 'Chelmsford 1',
      'win': '8'
    },
    {
      '_id': 'F:Canterbury 2',
      'against': '11',
      'division': 'prem',
      'draw': '2',
      'for': '16',
      'gender': 'F',
      'goal_difference': '5',
      'lose': '3',
      'played': '12',
      'points': '23',
      'team': 'Canterbury 2',
      'win': '7'
    },
    {
      '_id': 'F:Brom & Becks 1',
      'against': '18',
      'division': 'prem',
      'draw': '1',
      'for': '42',
      'gender': 'F',
      'goal_difference': '24',
      'lose': '2',
      'played': '10',
      'points': '22',
      'team': 'Brom & Becks 1',
      'win': '7'
    },
    {
      '_id': 'F:Broxbourne 1',
      'against': '11',
      'division': 'prem',
      'draw': '1',
      'for': '23',
      'gender': 'F',
      'goal_difference': '12',
      'lose': '3',
      'played': '11',
      'points': '22',
      'team': 'Broxbourne 1',
      'win': '7'
    },
    {
      '_id': 'F:CoP 1',
      'against': '18',
      'division': 'prem',
      'draw': '2',
      'for': '18',
      'gender': 'F',
      'goal_difference': '0',
      'lose': '4',
      'played': '12',
      'points': '20',
      'team': 'CoP 1',
      'win': '6'
    },
    {
      '_id': 'F:Cambridge City 2',
      'against': '16',
      'division': 'prem',
      'draw': '4',
      'for': '20',
      'gender': 'F',
      'goal_difference': '4',
      'lose': '3',
      'played': '12',
      'points': '19',
      'team': 'Cambridge City 2',
      'win': '5'
    },
    {
      '_id': 'F:Wapping 1',
      'against': '16',
      'division': 'prem',
      'draw': '2',
      'for': '14',
      'gender': 'F',
      'goal_difference': '-2',
      'lose': '5',
      'played': '11',
      'points': '14',
      'team': 'Wapping 1',
      'win': '4'
    },
    {
      '_id': 'F:St Albans 2',
      'against': '28',
      'division': 'prem',
      'draw': '3',
      'for': '23',
      'gender': 'F',
      'goal_difference': '-5',
      'lose': '6',
      'played': '12',
      'points': '12',
      'team': 'St Albans 2',
      'win': '3'
    },
    {
      '_id': 'F:Harleston Magpies 2',
      'against': '25',
      'division': 'prem',
      'draw': '5',
      'for': '17',
      'gender': 'F',
      'goal_difference': '-8',
      'lose': '5',
      'played': '12',
      'points': '11',
      'team': 'Harleston Magpies 2',
      'win': '2'
    },
    {
      '_id': 'F:Norwich City 1',
      'against': '27',
      'division': 'prem',
      'draw': '1',
      'for': '10',
      'gender': 'F',
      'goal_difference': '-17',
      'lose': '7',
      'played': '11',
      'points': '10',
      'team': 'Norwich City 1',
      'win': '3'
    },
    {
      '_id': 'F:West Herts 1',
      'against': '28',
      'division': 'prem',
      'draw': '3',
      'for': '19',
      'gender': 'F',
      'goal_difference': '-9',
      'lose': '6',
      'played': '11',
      'points': '9',
      'team': 'West Herts 1',
      'win': '2'
    },
    {
      '_id': 'F:Sevenoaks 2',
      'against': '23',
      'division': 'prem',
      'draw': '2',
      'for': '10',
      'gender': 'F',
      'goal_difference': '-13',
      'lose': '9',
      'played': '12',
      'points': '5',
      'team': 'Sevenoaks 2',
      'win': '1'
    },
    {
      '_id': 'F:East London 1',
      'against': '9',
      'division': '1s',
      'draw': '2',
      'for': '44',
      'gender': 'F',
      'goal_difference': '35',
      'lose': '1',
      'played': '12',
      'points': '29',
      'team': 'East London 1',
      'win': '9'
    },
    {
      '_id': 'F:Maidstone 1',
      'against': '21',
      'division': '1s',
      'draw': '1',
      'for': '55',
      'gender': 'F',
      'goal_difference': '34',
      'lose': '2',
      'played': '12',
      'points': '28',
      'team': 'Maidstone 1',
      'win': '9'
    },
    {
      '_id': 'F:Upminster 1',
      'against': '7',
      'division': '1s',
      'draw': '1',
      'for': '29',
      'gender': 'F',
      'goal_difference': '22',
      'lose': '1',
      'played': '11',
      'points': '28',
      'team': 'Upminster 1',
      'win': '9'
    },
    {
      '_id': 'F:Blueharts 1',
      'against': '18',
      'division': '1s',
      'draw': '3',
      'for': '31',
      'gender': 'F',
      'goal_difference': '13',
      'lose': '1',
      'played': '11',
      'points': '24',
      'team': 'Blueharts 1',
      'win': '7'
    },
    {
      '_id': 'F:Chelmsford 2',
      'against': '22',
      'division': '1s',
      'draw': '2',
      'for': '17',
      'gender': 'F',
      'goal_difference': '-5',
      'lose': '4',
      'played': '11',
      'points': '17',
      'team': 'Chelmsford 2',
      'win': '5'
    },
    {
      '_id': 'F:Bishops Stortford 1',
      'against': '19',
      'division': '1s',
      'draw': '3',
      'for': '24',
      'gender': 'F',
      'goal_difference': '5',
      'lose': '4',
      'played': '11',
      'points': '15',
      'team': 'Bishops Stortford 1',
      'win': '4'
    },
    {
      '_id': 'F:Crostyx 1',
      'against': '16',
      'division': '1s',
      'draw': '3',
      'for': '10',
      'gender': 'F',
      'goal_difference': '-6',
      'lose': '4',
      'played': '11',
      'points': '15',
      'team': 'Crostyx 1',
      'win': '4'
    },
    {
      '_id': 'F:Old Loughts 1',
      'against': '19',
      'division': '1s',
      'draw': '3',
      'for': '16',
      'gender': 'F',
      'goal_difference': '-3',
      'lose': '5',
      'played': '11',
      'points': '12',
      'team': 'Old Loughts 1',
      'win': '3'
    },
    {
      '_id': 'F:Tunbridge Wells 1',
      'against': '35',
      'division': '1s',
      'draw': '2',
      'for': '11',
      'gender': 'F',
      'goal_difference': '-24',
      'lose': '8',
      'played': '12',
      'points': '8',
      'team': 'Tunbridge Wells 1',
      'win': '2'
    },
    {
      '_id': 'F:Ashford 1',
      'against': '41',
      'division': '1s',
      'draw': '1',
      'for': '15',
      'gender': 'F',
      'goal_difference': '-26',
      'lose': '9',
      'played': '12',
      'points': '7',
      'team': 'Ashford 1',
      'win': '2'
    },
    {
      '_id': 'F:Colchester 1',
      'against': '37',
      'division': '1s',
      'draw': '0',
      'for': '16',
      'gender': 'F',
      'goal_difference': '-21',
      'lose': '10',
      'played': '12',
      'points': '6',
      'team': 'Colchester 1',
      'win': '2'
    },
    {
      '_id': 'F:Canterbury 2A',
      'against': '34',
      'division': '1s',
      'draw': '3',
      'for': '10',
      'gender': 'F',
      'goal_difference': '-24',
      'lose': '7',
      'played': '10',
      'points': '3',
      'team': 'Canterbury 2A',
      'win': '0'
    },
    {
      '_id': 'F:North Norfolk 1',
      'against': '12',
      'division': '2ne',
      'draw': '1',
      'for': '45',
      'gender': 'F',
      'goal_difference': '33',
      'lose': '1',
      'played': '12',
      'points': '31',
      'team': 'North Norfolk 1',
      'win': '10'
    },
    {
      '_id': 'F:Watton 1',
      'against': '13',
      'division': '2ne',
      'draw': '1',
      'for': '43',
      'gender': 'F',
      'goal_difference': '30',
      'lose': '1',
      'played': '12',
      'points': '31',
      'team': 'Watton 1',
      'win': '10'
    },
    {
      '_id': 'F:Bury St Edmunds 1',
      'against': '13',
      'division': '2ne',
      'draw': '0',
      'for': '36',
      'gender': 'F',
      'goal_difference': '23',
      'lose': '3',
      'played': '12',
      'points': '27',
      'team': 'Bury St Edmunds 1',
      'win': '9'
    },
    {
      '_id': 'F:Norwich Dragons 2',
      'against': '15',
      'division': '2ne',
      'draw': '0',
      'for': '32',
      'gender': 'F',
      'goal_difference': '17',
      'lose': '3',
      'played': '12',
      'points': '27',
      'team': 'Norwich Dragons 2',
      'win': '9'
    },
    {
      '_id': 'F:Harleston Magpies 3',
      'against': '20',
      'division': '2ne',
      'draw': '3',
      'for': '23',
      'gender': 'F',
      'goal_difference': '3',
      'lose': '4',
      'played': '12',
      'points': '18',
      'team': 'Harleston Magpies 3',
      'win': '5'
    },
    {
      '_id': 'F:UEA Women 1',
      'against': '36',
      'division': '2ne',
      'draw': '2',
      'for': '41',
      'gender': 'F',
      'goal_difference': '5',
      'lose': '5',
      'played': '12',
      'points': '17',
      'team': 'UEA Women 1',
      'win': '5'
    },
    {
      '_id': 'F:Norwich City 2',
      'against': '15',
      'division': '2ne',
      'draw': '0',
      'for': '20',
      'gender': 'F',
      'goal_difference': '5',
      'lose': '7',
      'played': '12',
      'points': '15',
      'team': 'Norwich City 2',
      'win': '5'
    },
    {
      '_id': 'F:Norwich Dragons 3',
      'against': '41',
      'division': '2ne',
      'draw': '0',
      'for': '19',
      'gender': 'F',
      'goal_difference': '-22',
      'lose': '7',
      'played': '12',
      'points': '15',
      'team': 'Norwich Dragons 3',
      'win': '5'
    },
    {
      '_id': 'F:Christchurch 1',
      'against': '24',
      'division': '2ne',
      'draw': '2',
      'for': '20',
      'gender': 'F',
      'goal_difference': '-4',
      'lose': '6',
      'played': '12',
      'points': '14',
      'team': 'Christchurch 1',
      'win': '4'
    },
    {
      '_id': 'F:Yarmouth 1',
      'against': '27',
      'division': '2ne',
      'draw': '2',
      'for': '20',
      'gender': 'F',
      'goal_difference': '-7',
      'lose': '7',
      'played': '12',
      'points': '11',
      'team': 'Yarmouth 1',
      'win': '3'
    },
    {
      '_id': 'F:Dereham 2',
      'against': '24',
      'division': '2ne',
      'draw': '1',
      'for': '8',
      'gender': 'F',
      'goal_difference': '-16',
      'lose': '10',
      'played': '12',
      'points': '4',
      'team': 'Dereham 2',
      'win': '1'
    },
    {
      '_id': 'F:Felixstowe 1',
      'against': '68',
      'division': '2ne',
      'draw': '0',
      'for': '1',
      'gender': 'F',
      'goal_difference': '-67',
      'lose': '12',
      'played': '12',
      'points': '0',
      'team': 'Felixstowe 1',
      'win': '0'
    },
    {
      '_id': 'F:CoP 2',
      'against': '5',
      'division': '2nw',
      'draw': '1',
      'for': '53',
      'gender': 'F',
      'goal_difference': '48',
      'lose': '0',
      'played': '12',
      'points': '34',
      'team': 'CoP 2',
      'win': '11'
    },
    {
      '_id': 'F:St Ives 1',
      'against': '16',
      'division': '2nw',
      'draw': '3',
      'for': '27',
      'gender': 'F',
      'goal_difference': '11',
      'lose': '2',
      'played': '12',
      'points': '24',
      'team': 'St Ives 1',
      'win': '7'
    },
    {
      '_id': 'F:Cambridge Nomads 1',
      'against': '15',
      'division': '2nw',
      'draw': '2',
      'for': '27',
      'gender': 'F',
      'goal_difference': '12',
      'lose': '3',
      'played': '12',
      'points': '23',
      'team': 'Cambridge Nomads 1',
      'win': '7'
    },
    {
      '_id': 'F:Cambridge South 1',
      'against': '22',
      'division': '2nw',
      'draw': '2',
      'for': '28',
      'gender': 'F',
      'goal_difference': '6',
      'lose': '4',
      'played': '12',
      'points': '20',
      'team': 'Cambridge South 1',
      'win': '6'
    },
    {
      '_id': 'F:Cambridge City 4',
      'against': '19',
      'division': '2nw',
      'draw': '2',
      'for': '20',
      'gender': 'F',
      'goal_difference': '1',
      'lose': '5',
      'played': '12',
      'points': '17',
      'team': 'Cambridge City 4',
      'win': '5'
    },
    {
      '_id': 'F:Bourne Deeping 1',
      'against': '21',
      'division': '2nw',
      'draw': '2',
      'for': '21',
      'gender': 'F',
      'goal_difference': '0',
      'lose': '5',
      'played': '12',
      'points': '17',
      'team': 'Bourne Deeping 1',
      'win': '5'
    },
    {
      '_id': 'F:Pelicans 1',
      'against': '21',
      'division': '2nw',
      'draw': '1',
      'for': '36',
      'gender': 'F',
      'goal_difference': '15',
      'lose': '6',
      'played': '12',
      'points': '16',
      'team': 'Pelicans 1',
      'win': '5'
    },
    {
      '_id': 'F:St Ives 2',
      'against': '37',
      'division': '2nw',
      'draw': '0',
      'for': '24',
      'gender': 'F',
      'goal_difference': '-13',
      'lose': '7',
      'played': '12',
      'points': '15',
      'team': 'St Ives 2',
      'win': '5'
    },
    {
      '_id': 'F:Spalding 1',
      'against': '28',
      'division': '2nw',
      'draw': '2',
      'for': '15',
      'gender': 'F',
      'goal_difference': '-13',
      'lose': '6',
      'played': '12',
      'points': '14',
      'team': 'Spalding 1',
      'win': '4'
    },
    {
      '_id': 'F:Long Sutton 1',
      'against': '29',
      'division': '2nw',
      'draw': '1',
      'for': '20',
      'gender': 'F',
      'goal_difference': '-9',
      'lose': '8',
      'played': '12',
      'points': '10',
      'team': 'Long Sutton 1',
      'win': '3'
    },
    {
      '_id': 'F:Alford & District 1',
      'against': '45',
      'division': '2nw',
      'draw': '0',
      'for': '18',
      'gender': 'F',
      'goal_difference': '-27',
      'lose': '9',
      'played': '12',
      'points': '9',
      'team': 'Alford & District 1',
      'win': '3'
    },
    {
      '_id': 'F:Newmarket 1',
      'against': '38',
      'division': '2nw',
      'draw': '0',
      'for': '7',
      'gender': 'F',
      'goal_difference': '-31',
      'lose': '9',
      'played': '12',
      'points': '9',
      'team': 'Newmarket 1',
      'win': '3'
    },
    {
      '_id': 'F:Basildon 1',
      'against': '11',
      'division': '2se',
      'draw': '1',
      'for': '32',
      'gender': 'F',
      'goal_difference': '21',
      'lose': '1',
      'played': '11',
      'points': '28',
      'team': 'Basildon 1',
      'win': '9'
    },
    {
      '_id': 'F:Burnt Ash 1',
      'against': '11',
      'division': '2se',
      'draw': '0',
      'for': '36',
      'gender': 'F',
      'goal_difference': '25',
      'lose': '2',
      'played': '11',
      'points': '27',
      'team': 'Burnt Ash 1',
      'win': '9'
    },
    {
      '_id': 'F:Folkestone 1',
      'against': '14',
      'division': '2se',
      'draw': '1',
      'for': '29',
      'gender': 'F',
      'goal_difference': '15',
      'lose': '3',
      'played': '11',
      'points': '22',
      'team': 'Folkestone 1',
      'win': '7'
    },
    {
      '_id': 'F:Holcombe 1A',
      'against': '10',
      'division': '2se',
      'draw': '2',
      'for': '21',
      'gender': 'F',
      'goal_difference': '11',
      'lose': '2',
      'played': '10',
      'points': '20',
      'team': 'Holcombe 1A',
      'win': '6'
    },
    {
      '_id': 'F:Kings and Alleyns 1',
      'against': '18',
      'division': '2se',
      'draw': '1',
      'for': '24',
      'gender': 'F',
      'goal_difference': '6',
      'lose': '5',
      'played': '11',
      'points': '16',
      'team': 'Kings and Alleyns 1',
      'win': '5'
    },
    {
      '_id': 'F:Brom & Becks 2',
      'against': '26',
      'division': '2se',
      'draw': '1',
      'for': '23',
      'gender': 'F',
      'goal_difference': '-3',
      'lose': '5',
      'played': '11',
      'points': '16',
      'team': 'Brom & Becks 2',
      'win': '5'
    },
    {
      '_id': 'F:Sevenoaks 3',
      'against': '13',
      'division': '2se',
      'draw': '2',
      'for': '23',
      'gender': 'F',
      'goal_difference': '10',
      'lose': '5',
      'played': '11',
      'points': '14',
      'team': 'Sevenoaks 3',
      'win': '4'
    },
    {
      '_id': 'F:Southend 1',
      'against': '21',
      'division': '2se',
      'draw': '1',
      'for': '22',
      'gender': 'F',
      'goal_difference': '1',
      'lose': '6',
      'played': '11',
      'points': '13',
      'team': 'Southend 1',
      'win': '4'
    },
    {
      '_id': 'F:Havering 1',
      'against': '44',
      'division': '2se',
      'draw': '2',
      'for': '26',
      'gender': 'F',
      'goal_difference': '-18',
      'lose': '7',
      'played': '11',
      'points': '8',
      'team': 'Havering 1',
      'win': '2'
    },
    {
      '_id': 'F:Southend & Benfleet 1',
      'against': '33',
      'division': '2se',
      'draw': '3',
      'for': '17',
      'gender': 'F',
      'goal_difference': '-16',
      'lose': '7',
      'played': '11',
      'points': '6',
      'team': 'Southend & Benfleet 1',
      'win': '1'
    },
    {
      '_id': 'F:Redbridge & Ilford 1',
      'against': '60',
      'division': '2se',
      'draw': '0',
      'for': '8',
      'gender': 'F',
      'goal_difference': '-52',
      'lose': '10',
      'played': '11',
      'points': '3',
      'team': 'Redbridge & Ilford 1',
      'win': '1'
    },
    {
      '_id': 'F:Tunbridge Wells 2',
      'against': '',
      'division': '2se',
      'draw': '0',
      'for': '',
      'gender': 'F',
      'goal_difference': '',
      'lose': '0',
      'played': '0',
      'points': '0',
      'team': 'Tunbridge Wells 2',
      'win': '0'
    },
    {
      '_id': 'F:Letchworth 1',
      'against': '14',
      'division': '2sw',
      'draw': '3',
      'for': '38',
      'gender': 'F',
      'goal_difference': '24',
      'lose': '0',
      'played': '11',
      'points': '27',
      'team': 'Letchworth 1',
      'win': '8'
    },
    {
      '_id': 'F:Wapping 2',
      'against': '6',
      'division': '2sw',
      'draw': '2',
      'for': '22',
      'gender': 'F',
      'goal_difference': '16',
      'lose': '2',
      'played': '11',
      'points': '23',
      'team': 'Wapping 2',
      'win': '7'
    },
    {
      '_id': 'F:Waltham Forest 1',
      'against': '20',
      'division': '2sw',
      'draw': '2',
      'for': '31',
      'gender': 'F',
      'goal_difference': '11',
      'lose': '3',
      'played': '11',
      'points': '20',
      'team': 'Waltham Forest 1',
      'win': '6'
    },
    {
      '_id': 'F:St Albans 3',
      'against': '19',
      'division': '2sw',
      'draw': '5',
      'for': '25',
      'gender': 'F',
      'goal_difference': '6',
      'lose': '2',
      'played': '11',
      'points': '17',
      'team': 'St Albans 3',
      'win': '4'
    },
    {
      '_id': 'F:Brentwood 1',
      'against': '11',
      'division': '2sw',
      'draw': '4',
      'for': '14',
      'gender': 'F',
      'goal_difference': '3',
      'lose': '2',
      'played': '10',
      'points': '16',
      'team': 'Brentwood 1',
      'win': '4'
    },
    {
      '_id': 'F:East London 2',
      'against': '21',
      'division': '2sw',
      'draw': '4',
      'for': '23',
      'gender': 'F',
      'goal_difference': '2',
      'lose': '3',
      'played': '11',
      'points': '16',
      'team': 'East London 2',
      'win': '4'
    },
    {
      '_id': 'F:Stevenage 1',
      'against': '20',
      'division': '2sw',
      'draw': '2',
      'for': '25',
      'gender': 'F',
      'goal_difference': '5',
      'lose': '5',
      'played': '11',
      'points': '14',
      'team': 'Stevenage 1',
      'win': '4'
    },
    {
      '_id': 'F:Shefford & Sandy 1',
      'against': '27',
      'division': '2sw',
      'draw': '1',
      'for': '18',
      'gender': 'F',
      'goal_difference': '-9',
      'lose': '6',
      'played': '11',
      'points': '13',
      'team': 'Shefford & Sandy 1',
      'win': '4'
    },
    {
      '_id': 'F:Leighton Buzzard 1',
      'against': '34',
      'division': '2sw',
      'draw': '2',
      'for': '13',
      'gender': 'F',
      'goal_difference': '-21',
      'lose': '7',
      'played': '11',
      'points': '8',
      'team': 'Leighton Buzzard 1',
      'win': '2'
    },
    {
      '_id': 'F:West Herts 2',
      'against': '26',
      'division': '2sw',
      'draw': '4',
      'for': '14',
      'gender': 'F',
      'goal_difference': '-12',
      'lose': '6',
      'played': '11',
      'points': '7',
      'team': 'West Herts 2',
      'win': '1'
    },
    {
      '_id': 'F:Harpenden 1',
      'against': '34',
      'division': '2sw',
      'draw': '3',
      'for': '9',
      'gender': 'F',
      'goal_difference': '-25',
      'lose': '8',
      'played': '11',
      'points': '3',
      'team': 'Harpenden 1',
      'win': '0'
    },
    {
      '_id': 'F:Old Loughts 2',
      'against': '',
      'division': '2sw',
      'draw': '0',
      'for': '',
      'gender': 'F',
      'goal_difference': '',
      'lose': '0',
      'played': '0',
      'points': '0',
      'team': 'Old Loughts 2',
      'win': '0'
    },
    {
      '_id': 'F:Ely City 2',
      'against': '9',
      'division': '5nw(s)',
      'draw': '0',
      'for': '70',
      'gender': 'F',
      'goal_difference': '61',
      'lose': '0',
      'played': '10',
      'points': '30',
      'team': 'Ely City 2',
      'win': '10'
    },
    {
      '_id': 'F:Cambridge City 6',
      'against': '10',
      'division': '5nw(s)',
      'draw': '0',
      'for': '52',
      'gender': 'F',
      'goal_difference': '42',
      'lose': '2',
      'played': '11',
      'points': '27',
      'team': 'Cambridge City 6',
      'win': '9'
    },
    {
      '_id': 'F:St Ives 4',
      'against': '11',
      'division': '5nw(s)',
      'draw': '1',
      'for': '36',
      'gender': 'F',
      'goal_difference': '25',
      'lose': '2',
      'played': '11',
      'points': '25',
      'team': 'St Ives 4',
      'win': '8'
    },
    {
      '_id': 'F:Newmarket 3',
      'against': '16',
      'division': '5nw(s)',
      'draw': '1',
      'for': '19',
      'gender': 'F',
      'goal_difference': '3',
      'lose': '3',
      'played': '11',
      'points': '22',
      'team': 'Newmarket 3',
      'win': '7'
    },
    {
      '_id': 'F:Bury St Edmunds 4',
      'against': '37',
      'division': '5nw(s)',
      'draw': '2',
      'for': '45',
      'gender': 'F',
      'goal_difference': '8',
      'lose': '4',
      'played': '11',
      'points': '17',
      'team': 'Bury St Edmunds 4',
      'win': '5'
    },
    {
      '_id': 'F:Cambridge South 4',
      'against': '34',
      'division': '5nw(s)',
      'draw': '0',
      'for': '18',
      'gender': 'F',
      'goal_difference': '-16',
      'lose': '7',
      'played': '11',
      'points': '12',
      'team': 'Cambridge South 4',
      'win': '4'
    },
    {
      '_id': 'F:Sudbury 3',
      'against': '29',
      'division': '5nw(s)',
      'draw': '1',
      'for': '34',
      'gender': 'F',
      'goal_difference': '5',
      'lose': '5',
      'played': '11',
      'points': '10',
      'team': 'Sudbury 3',
      'win': '5'
    },
    {
      '_id': 'F:Wisbech Town 3',
      'against': '40',
      'division': '5nw(s)',
      'draw': '0',
      'for': '10',
      'gender': 'F',
      'goal_difference': '-30',
      'lose': '8',
      'played': '11',
      'points': '9',
      'team': 'Wisbech Town 3',
      'win': '3'
    },
    {
      '_id': 'F:Huntingdon 2',
      'against': '33',
      'division': '5nw(s)',
      'draw': '1',
      'for': '19',
      'gender': 'F',
      'goal_difference': '-14',
      'lose': '7',
      'played': '11',
      'points': '7',
      'team': 'Huntingdon 2',
      'win': '3'
    },
    {
      '_id': 'F:Ely City 3',
      'against': '42',
      'division': '5nw(s)',
      'draw': '0',
      'for': '7',
      'gender': 'F',
      'goal_difference': '-35',
      'lose': '10',
      'played': '11',
      'points': '3',
      'team': 'Ely City 3',
      'win': '1'
    },
    {
      '_id': 'F:Newmarket 4',
      'against': '60',
      'division': '5nw(s)',
      'draw': '0',
      'for': '11',
      'gender': 'F',
      'goal_difference': '-49',
      'lose': '9',
      'played': '11',
      'points': '3',
      'team': 'Newmarket 4',
      'win': '2'
    }
  ]
}
