module.exports = function () {
  return [
    {
      '_id': 'M:Brentwood 1',
      'against': '7',
      'division': '3se',
      'draw': '0',
      'for': '31',
      'gender': 'M',
      'goal_difference': '24',
      'lose': '0',
      'played': '6',
      'points': '18',
      'team': 'Brentwood 1',
      'win': '6'
    },
    {
      '_id': 'M:Wapping 5',
      'against': '7',
      'division': '3se',
      'draw': '1',
      'for': '27',
      'gender': 'M',
      'goal_difference': '20',
      'lose': '0',
      'played': '6',
      'points': '16',
      'team': 'Wapping 5',
      'win': '5'
    },
    {
      '_id': 'M:Braintree 1',
      'against': '12',
      'division': '3se',
      'draw': '1',
      'for': '17',
      'gender': 'M',
      'goal_difference': '5',
      'lose': '1',
      'played': '6',
      'points': '13',
      'team': 'Braintree 1',
      'win': '4'
    },
    {
      '_id': 'M:Upminster 2',
      'against': '11',
      'division': '3se',
      'draw': '2',
      'for': '13',
      'gender': 'M',
      'goal_difference': '2',
      'lose': '1',
      'played': '6',
      'points': '11',
      'team': 'Upminster 2',
      'win': '3'
    },
    {
      '_id': 'M:Redbridge & Ilford 1',
      'against': '12',
      'division': '3se',
      'draw': '0',
      'for': '17',
      'gender': 'M',
      'goal_difference': '5',
      'lose': '3',
      'played': '6',
      'points': '9',
      'team': 'Redbridge & Ilford 1',
      'win': '3'
    },
    {
      '_id': 'M:Southend 1',
      'against': '13',
      'division': '3se',
      'draw': '3',
      'for': '16',
      'gender': 'M',
      'goal_difference': '3',
      'lose': '1',
      'played': '6',
      'points': '9',
      'team': 'Southend 1',
      'win': '2'
    },
    {
      '_id': 'M:Wapping 6',
      'against': '12',
      'division': '3se',
      'draw': '2',
      'for': '13',
      'gender': 'M',
      'goal_difference': '1',
      'lose': '2',
      'played': '6',
      'points': '8',
      'team': 'Wapping 6',
      'win': '2'
    },
    {
      '_id': 'M:Maldon 1',
      'against': '21',
      'division': '3se',
      'draw': '0',
      'for': '14',
      'gender': 'M',
      'goal_difference': '-7',
      'lose': '4',
      'played': '6',
      'points': '6',
      'team': 'Maldon 1',
      'win': '2'
    },
    {
      '_id': 'M:Clacton 1',
      'against': '21',
      'division': '3se',
      'draw': '1',
      'for': '10',
      'gender': 'M',
      'goal_difference': '-11',
      'lose': '4',
      'played': '6',
      'points': '4',
      'team': 'Clacton 1',
      'win': '1'
    },
    {
      '_id': 'M:East London 3',
      'against': '20',
      'division': '3se',
      'draw': '0',
      'for': '11',
      'gender': 'M',
      'goal_difference': '-9',
      'lose': '5',
      'played': '6',
      'points': '3',
      'team': 'East London 3',
      'win': '1'
    },
    {
      '_id': 'M:Crostyx 2',
      'against': '22',
      'division': '3se',
      'draw': '0',
      'for': '6',
      'gender': 'M',
      'goal_difference': '-16',
      'lose': '5',
      'played': '6',
      'points': '3',
      'team': 'Crostyx 2',
      'win': '1'
    },
    {
      '_id': 'M:Brentwood 2',
      'against': '29',
      'division': '3se',
      'draw': '0',
      'for': '12',
      'gender': 'M',
      'goal_difference': '-17',
      'lose': '5',
      'played': '6',
      'points': '3',
      'team': 'Brentwood 2',
      'win': '1'
    },
    {
      '_id': 'M:Saffron Walden 3',
      'against': '12',
      'division': '4se',
      'draw': '1',
      'for': '30',
      'gender': 'M',
      'goal_difference': '18',
      'lose': '0',
      'played': '6',
      'points': '16',
      'team': 'Saffron Walden 3',
      'win': '5'
    },
    {
      '_id': 'M:Plashet 1',
      'against': '10',
      'division': '4se',
      'draw': '0',
      'for': '35',
      'gender': 'M',
      'goal_difference': '25',
      'lose': '1',
      'played': '6',
      'points': '15',
      'team': 'Plashet 1',
      'win': '5'
    },
    {
      '_id': 'M:Chelmsford 3',
      'against': '8',
      'division': '4se',
      'draw': '0',
      'for': '19',
      'gender': 'M',
      'goal_difference': '11',
      'lose': '1',
      'played': '6',
      'points': '15',
      'team': 'Chelmsford 3',
      'win': '5'
    },
    {
      '_id': 'M:Waltham Forest 2',
      'against': '10',
      'division': '4se',
      'draw': '0',
      'for': '18',
      'gender': 'M',
      'goal_difference': '8',
      'lose': '2',
      'played': '6',
      'points': '12',
      'team': 'Waltham Forest 2',
      'win': '4'
    },
    {
      '_id': 'M:Wapping 7',
      'against': '8',
      'division': '4se',
      'draw': '0',
      'for': '13',
      'gender': 'M',
      'goal_difference': '5',
      'lose': '2',
      'played': '6',
      'points': '12',
      'team': 'Wapping 7',
      'win': '4'
    },
    {
      '_id': 'M:East London 4',
      'against': '10',
      'division': '4se',
      'draw': '0',
      'for': '11',
      'gender': 'M',
      'goal_difference': '1',
      'lose': '3',
      'played': '6',
      'points': '9',
      'team': 'East London 4',
      'win': '3'
    },
    {
      '_id': 'M:Witham 2',
      'against': '15',
      'division': '4se',
      'draw': '2',
      'for': '17',
      'gender': 'M',
      'goal_difference': '2',
      'lose': '2',
      'played': '6',
      'points': '8',
      'team': 'Witham 2',
      'win': '2'
    },
    {
      '_id': 'M:Old Southendian 2',
      'against': '23',
      'division': '4se',
      'draw': '1',
      'for': '11',
      'gender': 'M',
      'goal_difference': '-12',
      'lose': '3',
      'played': '6',
      'points': '7',
      'team': 'Old Southendian 2',
      'win': '2'
    },
    {
      '_id': 'M:Romford 1',
      'against': '22',
      'division': '4se',
      'draw': '1',
      'for': '13',
      'gender': 'M',
      'goal_difference': '-9',
      'lose': '4',
      'played': '6',
      'points': '4',
      'team': 'Romford 1',
      'win': '1'
    },
    {
      '_id': 'M:Brentwood 3',
      'against': '25',
      'division': '4se',
      'draw': '1',
      'for': '6',
      'gender': 'M',
      'goal_difference': '-19',
      'lose': '4',
      'played': '6',
      'points': '4',
      'team': 'Brentwood 3',
      'win': '1'
    },
    {
      '_id': 'M:Havering 2',
      'against': '22',
      'division': '4se',
      'draw': '0',
      'for': '8',
      'gender': 'M',
      'goal_difference': '-14',
      'lose': '5',
      'played': '6',
      'points': '3',
      'team': 'Havering 2',
      'win': '1'
    },
    {
      '_id': 'M:Colchester 2',
      'against': '23',
      'division': '4se',
      'draw': '0',
      'for': '7',
      'gender': 'M',
      'goal_difference': '-16',
      'lose': '6',
      'played': '6',
      'points': '0',
      'team': 'Colchester 2',
      'win': '0'
    },
    {
      '_id': 'M:Thurrock 1',
      'against': '5',
      'division': '5se',
      'draw': '0',
      'for': '25',
      'gender': 'M',
      'goal_difference': '20',
      'lose': '0',
      'played': '6',
      'points': '18',
      'team': 'Thurrock 1',
      'win': '6'
    },
    {
      '_id': 'M:Rochford 1',
      'against': '10',
      'division': '5se',
      'draw': '0',
      'for': '22',
      'gender': 'M',
      'goal_difference': '12',
      'lose': '1',
      'played': '6',
      'points': '15',
      'team': 'Rochford 1',
      'win': '5'
    },
    {
      '_id': 'M:Crostyx 3',
      'against': '7',
      'division': '5se',
      'draw': '1',
      'for': '23',
      'gender': 'M',
      'goal_difference': '16',
      'lose': '2',
      'played': '6',
      'points': '10',
      'team': 'Crostyx 3',
      'win': '3'
    },
    {
      '_id': 'M:Wapping 8',
      'against': '10',
      'division': '5se',
      'draw': '1',
      'for': '13',
      'gender': 'M',
      'goal_difference': '3',
      'lose': '2',
      'played': '6',
      'points': '10',
      'team': 'Wapping 8',
      'win': '3'
    },
    {
      '_id': 'M:Upminster 3',
      'against': '10',
      'division': '5se',
      'draw': '3',
      'for': '12',
      'gender': 'M',
      'goal_difference': '2',
      'lose': '1',
      'played': '6',
      'points': '9',
      'team': 'Upminster 3',
      'win': '2'
    },
    {
      '_id': 'M:Southend 2',
      'against': '16',
      'division': '5se',
      'draw': '2',
      'for': '16',
      'gender': 'M',
      'goal_difference': '0',
      'lose': '2',
      'played': '6',
      'points': '8',
      'team': 'Southend 2',
      'win': '2'
    },
    {
      '_id': 'M:Redbridge & Ilford 2',
      'against': '16',
      'division': '5se',
      'draw': '1',
      'for': '16',
      'gender': 'M',
      'goal_difference': '0',
      'lose': '3',
      'played': '6',
      'points': '7',
      'team': 'Redbridge & Ilford 2',
      'win': '2'
    },
    {
      '_id': 'M:Waltham Forest 3',
      'against': '16',
      'division': '5se',
      'draw': '1',
      'for': '14',
      'gender': 'M',
      'goal_difference': '-2',
      'lose': '3',
      'played': '6',
      'points': '7',
      'team': 'Waltham Forest 3',
      'win': '2'
    },
    {
      '_id': 'M:East London 5',
      'against': '16',
      'division': '5se',
      'draw': '1',
      'for': '11',
      'gender': 'M',
      'goal_difference': '-5',
      'lose': '3',
      'played': '6',
      'points': '7',
      'team': 'East London 5',
      'win': '2'
    },
    {
      '_id': 'M:Witham 3',
      'against': '19',
      'division': '5se',
      'draw': '0',
      'for': '9',
      'gender': 'M',
      'goal_difference': '-10',
      'lose': '4',
      'played': '6',
      'points': '6',
      'team': 'Witham 3',
      'win': '2'
    },
    {
      '_id': 'M:Old Southendian 3',
      'against': '17',
      'division': '5se',
      'draw': '2',
      'for': '8',
      'gender': 'M',
      'goal_difference': '-9',
      'lose': '3',
      'played': '6',
      'points': '5',
      'team': 'Old Southendian 3',
      'win': '1'
    },
    {
      '_id': 'M:Clacton 2',
      'against': '29',
      'division': '5se',
      'draw': '0',
      'for': '2',
      'gender': 'M',
      'goal_difference': '-27',
      'lose': '6',
      'played': '6',
      'points': '0',
      'team': 'Clacton 2',
      'win': '0'
    },
    {
      '_id': 'M:Old Loughts Academy',
      'against': '8',
      'division': '6se',
      'draw': '0',
      'for': '32',
      'gender': 'M',
      'goal_difference': '24',
      'lose': '0',
      'played': '6',
      'points': '18',
      'team': 'Old Loughts Academy',
      'win': '6'
    },
    {
      '_id': 'M:Chelmsford 4',
      'against': '13',
      'division': '6se',
      'draw': '1',
      'for': '27',
      'gender': 'M',
      'goal_difference': '14',
      'lose': '1',
      'played': '6',
      'points': '13',
      'team': 'Chelmsford 4',
      'win': '4'
    },
    {
      '_id': 'M:East London 7',
      'against': '9',
      'division': '6se',
      'draw': '0',
      'for': '28',
      'gender': 'M',
      'goal_difference': '19',
      'lose': '2',
      'played': '6',
      'points': '12',
      'team': 'East London 7',
      'win': '4'
    },
    {
      '_id': 'M:East London 6',
      'against': '8',
      'division': '6se',
      'draw': '1',
      'for': '18',
      'gender': 'M',
      'goal_difference': '10',
      'lose': '2',
      'played': '6',
      'points': '10',
      'team': 'East London 6',
      'win': '3'
    },
    {
      '_id': 'M:Saffron Walden 4',
      'against': '11',
      'division': '6se',
      'draw': '1',
      'for': '17',
      'gender': 'M',
      'goal_difference': '6',
      'lose': '2',
      'played': '6',
      'points': '10',
      'team': 'Saffron Walden 4',
      'win': '3'
    },
    {
      '_id': 'M:Wapping 9',
      'against': '18',
      'division': '6se',
      'draw': '0',
      'for': '13',
      'gender': 'M',
      'goal_difference': '-5',
      'lose': '3',
      'played': '6',
      'points': '9',
      'team': 'Wapping 9',
      'win': '3'
    },
    {
      '_id': 'M:Braintree 2',
      'against': '14',
      'division': '6se',
      'draw': '1',
      'for': '10',
      'gender': 'M',
      'goal_difference': '-4',
      'lose': '3',
      'played': '6',
      'points': '7',
      'team': 'Braintree 2',
      'win': '2'
    },
    {
      '_id': 'M:Chelmsford 5',
      'against': '18',
      'division': '6se',
      'draw': '0',
      'for': '15',
      'gender': 'M',
      'goal_difference': '-3',
      'lose': '4',
      'played': '6',
      'points': '6',
      'team': 'Chelmsford 5',
      'win': '2'
    },
    {
      '_id': 'M:Basildon 1',
      'against': '29',
      'division': '6se',
      'draw': '0',
      'for': '8',
      'gender': 'M',
      'goal_difference': '-21',
      'lose': '4',
      'played': '6',
      'points': '6',
      'team': 'Basildon 1',
      'win': '2'
    },
    {
      '_id': 'M:Colchester 3',
      'against': '25',
      'division': '6se',
      'draw': '2',
      'for': '14',
      'gender': 'M',
      'goal_difference': '-11',
      'lose': '3',
      'played': '6',
      'points': '5',
      'team': 'Colchester 3',
      'win': '1'
    },
    {
      '_id': 'M:Maldon 2',
      'against': '26',
      'division': '6se',
      'draw': '1',
      'for': '13',
      'gender': 'M',
      'goal_difference': '-13',
      'lose': '4',
      'played': '6',
      'points': '4',
      'team': 'Maldon 2',
      'win': '1'
    },
    {
      '_id': 'M:Brentwood 4',
      'against': '27',
      'division': '6se',
      'draw': '1',
      'for': '11',
      'gender': 'M',
      'goal_difference': '-16',
      'lose': '4',
      'played': '6',
      'points': '4',
      'team': 'Brentwood 4',
      'win': '1'
    },
    {
      '_id': 'M:Old Loughts Loppers',
      'against': '7',
      'division': '7se',
      'draw': '1',
      'for': '32',
      'gender': 'M',
      'goal_difference': '25',
      'lose': '0',
      'played': '6',
      'points': '16',
      'team': 'Old Loughts Loppers',
      'win': '5'
    },
    {
      '_id': 'M:Saffron Walden 5',
      'against': '9',
      'division': '7se',
      'draw': '1',
      'for': '23',
      'gender': 'M',
      'goal_difference': '14',
      'lose': '0',
      'played': '6',
      'points': '16',
      'team': 'Saffron Walden 5',
      'win': '5'
    },
    {
      '_id': 'M:Havering 3',
      'against': '7',
      'division': '7se',
      'draw': '1',
      'for': '33',
      'gender': 'M',
      'goal_difference': '26',
      'lose': '1',
      'played': '6',
      'points': '13',
      'team': 'Havering 3',
      'win': '4'
    },
    {
      '_id': 'M:Upminster 4',
      'against': '10',
      'division': '7se',
      'draw': '2',
      'for': '16',
      'gender': 'M',
      'goal_difference': '6',
      'lose': '1',
      'played': '6',
      'points': '11',
      'team': 'Upminster 4',
      'win': '3'
    },
    {
      '_id': 'M:Witham 4',
      'against': '19',
      'division': '7se',
      'draw': '0',
      'for': '13',
      'gender': 'M',
      'goal_difference': '-6',
      'lose': '3',
      'played': '6',
      'points': '9',
      'team': 'Witham 4',
      'win': '3'
    },
    {
      '_id': 'M:Redbridge & Ilford 3',
      'against': '9',
      'division': '7se',
      'draw': '2',
      'for': '9',
      'gender': 'M',
      'goal_difference': '0',
      'lose': '2',
      'played': '6',
      'points': '8',
      'team': 'Redbridge & Ilford 3',
      'win': '2'
    },
    {
      '_id': 'M:Chelmsford 6',
      'against': '16',
      'division': '7se',
      'draw': '1',
      'for': '14',
      'gender': 'M',
      'goal_difference': '-2',
      'lose': '3',
      'played': '6',
      'points': '7',
      'team': 'Chelmsford 6',
      'win': '2'
    },
    {
      '_id': 'M:Saffron Walden 6',
      'against': '15',
      'division': '7se',
      'draw': '1',
      'for': '11',
      'gender': 'M',
      'goal_difference': '-4',
      'lose': '3',
      'played': '6',
      'points': '7',
      'team': 'Saffron Walden 6',
      'win': '2'
    },
    {
      '_id': 'M:Witham Academy',
      'against': '21',
      'division': '7se',
      'draw': '1',
      'for': '12',
      'gender': 'M',
      'goal_difference': '-9',
      'lose': '3',
      'played': '6',
      'points': '7',
      'team': 'Witham Academy',
      'win': '2'
    },
    {
      '_id': 'M:Braintree 3',
      'against': '23',
      'division': '7se',
      'draw': '1',
      'for': '16',
      'gender': 'M',
      'goal_difference': '-7',
      'lose': '4',
      'played': '6',
      'points': '4',
      'team': 'Braintree 3',
      'win': '1'
    },
    {
      '_id': 'M:Wapping X',
      'against': '20',
      'division': '7se',
      'draw': '1',
      'for': '9',
      'gender': 'M',
      'goal_difference': '-11',
      'lose': '4',
      'played': '6',
      'points': '4',
      'team': 'Wapping X',
      'win': '1'
    },
    {
      '_id': 'M:Waltham Forest 4',
      'against': '37',
      'division': '7se',
      'draw': '0',
      'for': '5',
      'gender': 'M',
      'goal_difference': '-32',
      'lose': '6',
      'played': '6',
      'points': '0',
      'team': 'Waltham Forest 4',
      'win': '0'
    },
    {
      '_id': 'M:Tower Hamlets 1',
      'against': '2',
      'division': '8se',
      'draw': '0',
      'for': '41',
      'gender': 'M',
      'goal_difference': '39',
      'lose': '0',
      'played': '6',
      'points': '18',
      'team': 'Tower Hamlets 1',
      'win': '6'
    },
    {
      '_id': 'M:Romford 2',
      'against': '7',
      'division': '8se',
      'draw': '0',
      'for': '22',
      'gender': 'M',
      'goal_difference': '15',
      'lose': '1',
      'played': '6',
      'points': '15',
      'team': 'Romford 2',
      'win': '5'
    },
    {
      '_id': 'M:Wapping XI',
      'against': '9',
      'division': '8se',
      'draw': '1',
      'for': '18',
      'gender': 'M',
      'goal_difference': '9',
      'lose': '1',
      'played': '6',
      'points': '13',
      'team': 'Wapping XI',
      'win': '4'
    },
    {
      '_id': 'M:Old Southendian 4',
      'against': '8',
      'division': '8se',
      'draw': '2',
      'for': '16',
      'gender': 'M',
      'goal_difference': '8',
      'lose': '1',
      'played': '6',
      'points': '11',
      'team': 'Old Southendian 4',
      'win': '3'
    },
    {
      '_id': 'M:Brentwood Academy',
      'against': '14',
      'division': '8se',
      'draw': '2',
      'for': '8',
      'gender': 'M',
      'goal_difference': '-6',
      'lose': '2',
      'played': '6',
      'points': '8',
      'team': 'Brentwood Academy',
      'win': '2'
    },
    {
      '_id': 'M:East London 8',
      'against': '5',
      'division': '8se',
      'draw': '1',
      'for': '10',
      'gender': 'M',
      'goal_difference': '5',
      'lose': '3',
      'played': '6',
      'points': '7',
      'team': 'East London 8',
      'win': '2'
    },
    {
      '_id': 'M:Braintree Knights',
      'against': '16',
      'division': '8se',
      'draw': '1',
      'for': '16',
      'gender': 'M',
      'goal_difference': '0',
      'lose': '3',
      'played': '6',
      'points': '7',
      'team': 'Braintree Knights',
      'win': '2'
    },
    {
      '_id': 'M:Colchester 4',
      'against': '21',
      'division': '8se',
      'draw': '0',
      'for': '10',
      'gender': 'M',
      'goal_difference': '-11',
      'lose': '4',
      'played': '6',
      'points': '6',
      'team': 'Colchester 4',
      'win': '2'
    },
    {
      '_id': 'M:Saffron Walden 7',
      'against': '22',
      'division': '8se',
      'draw': '2',
      'for': '9',
      'gender': 'M',
      'goal_difference': '-13',
      'lose': '3',
      'played': '6',
      'points': '5',
      'team': 'Saffron Walden 7',
      'win': '1'
    },
    {
      '_id': 'M:Thurrock 2',
      'against': '27',
      'division': '8se',
      'draw': '1',
      'for': '8',
      'gender': 'M',
      'goal_difference': '-19',
      'lose': '4',
      'played': '6',
      'points': '4',
      'team': 'Thurrock 2',
      'win': '1'
    },
    {
      '_id': 'M:Old Southendian 5',
      'against': '17',
      'division': '8se',
      'draw': '0',
      'for': '5',
      'gender': 'M',
      'goal_difference': '-12',
      'lose': '4',
      'played': '6',
      'points': '3',
      'team': 'Old Southendian 5',
      'win': '2'
    },
    {
      '_id': 'M:Brentwood 5',
      'against': '23',
      'division': '8se',
      'draw': '2',
      'for': '8',
      'gender': 'M',
      'goal_difference': '-15',
      'lose': '4',
      'played': '6',
      'points': '2',
      'team': 'Brentwood 5',
      'win': '0'
    },
    {
      '_id': 'M:Old Loughts Willows 1',
      'against': '4',
      'division': '9se',
      'draw': '1',
      'for': '31',
      'gender': 'M',
      'goal_difference': '27',
      'lose': '0',
      'played': '6',
      'points': '16',
      'team': 'Old Loughts Willows 1',
      'win': '5'
    },
    {
      '_id': 'M:Upminster 5',
      'against': '18',
      'division': '9se',
      'draw': '0',
      'for': '18',
      'gender': 'M',
      'goal_difference': '0',
      'lose': '2',
      'played': '6',
      'points': '12',
      'team': 'Upminster 5',
      'win': '4'
    },
    {
      '_id': 'M:Southend 3',
      'against': '17',
      'division': '9se',
      'draw': '2',
      'for': '17',
      'gender': 'M',
      'goal_difference': '0',
      'lose': '1',
      'played': '6',
      'points': '11',
      'team': 'Southend 3',
      'win': '3'
    },
    {
      '_id': 'M:Crostyx 4',
      'against': '15',
      'division': '9se',
      'draw': '0',
      'for': '16',
      'gender': 'M',
      'goal_difference': '1',
      'lose': '3',
      'played': '6',
      'points': '9',
      'team': 'Crostyx 4',
      'win': '3'
    },
    {
      '_id': 'M:Havering 4',
      'against': '11',
      'division': '9se',
      'draw': '2',
      'for': '10',
      'gender': 'M',
      'goal_difference': '-1',
      'lose': '2',
      'played': '6',
      'points': '8',
      'team': 'Havering 4',
      'win': '2'
    },
    {
      '_id': 'M:Maldon Academy',
      'against': '18',
      'division': '9se',
      'draw': '2',
      'for': '9',
      'gender': 'M',
      'goal_difference': '-9',
      'lose': '3',
      'played': '6',
      'points': '5',
      'team': 'Maldon Academy',
      'win': '1'
    },
    {
      '_id': 'M:Rochford 2',
      'against': '19',
      'division': '9se',
      'draw': '1',
      'for': '9',
      'gender': 'M',
      'goal_difference': '-10',
      'lose': '4',
      'played': '6',
      'points': '4',
      'team': 'Rochford 2',
      'win': '1'
    },
    {
      '_id': 'M:London Royals 1',
      'against': '17',
      'division': '9se',
      'draw': '0',
      'for': '9',
      'gender': 'M',
      'goal_difference': '-8',
      'lose': '5',
      'played': '6',
      'points': '3',
      'team': 'London Royals 1',
      'win': '1'
    },
    {
      '_id': 'M:Braintree 5',
      'against': '6',
      'division': '10se',
      'draw': '2',
      'for': '24',
      'gender': 'M',
      'goal_difference': '18',
      'lose': '0',
      'played': '6',
      'points': '14',
      'team': 'Braintree 5',
      'win': '4'
    },
    {
      '_id': 'M:Old Loughts Willows 2',
      'against': '4',
      'division': '10se',
      'draw': '2',
      'for': '10',
      'gender': 'M',
      'goal_difference': '6',
      'lose': '1',
      'played': '6',
      'points': '11',
      'team': 'Old Loughts Willows 2',
      'win': '3'
    },
    {
      '_id': 'M:East London 9',
      'against': '10',
      'division': '10se',
      'draw': '1',
      'for': '11',
      'gender': 'M',
      'goal_difference': '1',
      'lose': '2',
      'played': '6',
      'points': '10',
      'team': 'East London 9',
      'win': '3'
    },
    {
      '_id': 'M:Chelmsford 7',
      'against': '5',
      'division': '10se',
      'draw': '3',
      'for': '12',
      'gender': 'M',
      'goal_difference': '7',
      'lose': '1',
      'played': '6',
      'points': '9',
      'team': 'Chelmsford 7',
      'win': '2'
    },
    {
      '_id': 'M:Romford 3',
      'against': '17',
      'division': '10se',
      'draw': '0',
      'for': '19',
      'gender': 'M',
      'goal_difference': '2',
      'lose': '3',
      'played': '6',
      'points': '9',
      'team': 'Romford 3',
      'win': '3'
    },
    {
      '_id': 'M:Old Southendian 6',
      'against': '13',
      'division': '10se',
      'draw': '0',
      'for': '14',
      'gender': 'M',
      'goal_difference': '1',
      'lose': '3',
      'played': '6',
      'points': '9',
      'team': 'Old Southendian 6',
      'win': '3'
    },
    {
      '_id': 'M:Saffron Walden 8',
      'against': '20',
      'division': '10se',
      'draw': '0',
      'for': '7',
      'gender': 'M',
      'goal_difference': '-13',
      'lose': '5',
      'played': '6',
      'points': '3',
      'team': 'Saffron Walden 8',
      'win': '1'
    },
    {
      '_id': 'M:Waltham Forest 5',
      'against': '25',
      'division': '10se',
      'draw': '2',
      'for': '3',
      'gender': 'M',
      'goal_difference': '-22',
      'lose': '4',
      'played': '6',
      'points': '2',
      'team': 'Waltham Forest 5',
      'win': '0'
    }
  ]
}
