module.exports = function () {
  return [
    {
      _id: 'Brentwood 1',
      division: '3se',
      played: '6',
      win: '6',
      draw: '0',
      lose: '0',
      for: '31',
      against: '7',
      goal_difference: '24',
      points: '18'
    },
    {
      _id: 'Wapping 5',
      division: '3se',
      played: '6',
      win: '5',
      draw: '1',
      lose: '0',
      for: '27',
      against: '7',
      goal_difference: '20',
      points: '16'
    },
    {
      _id: 'Braintree 1',
      division: '3se',
      played: '6',
      win: '4',
      draw: '1',
      lose: '1',
      for: '17',
      against: '12',
      goal_difference: '5',
      points: '13'
    },
    {
      _id: 'Upminster 2',
      division: '3se',
      played: '6',
      win: '3',
      draw: '2',
      lose: '1',
      for: '13',
      against: '11',
      goal_difference: '2',
      points: '11'
    },
    {
      _id: 'Redbridge & Ilford 1',
      division: '3se',
      played: '6',
      win: '3',
      draw: '0',
      lose: '3',
      for: '17',
      against: '12',
      goal_difference: '5',
      points: '9'
    },
    {
      _id: 'Southend 1',
      division: '3se',
      played: '6',
      win: '2',
      draw: '3',
      lose: '1',
      for: '16',
      against: '13',
      goal_difference: '3',
      points: '9'
    },
    {
      _id: 'Wapping 6',
      division: '3se',
      played: '6',
      win: '2',
      draw: '2',
      lose: '2',
      for: '13',
      against: '12',
      goal_difference: '1',
      points: '8'
    },
    {
      _id: 'Maldon 1',
      division: '3se',
      played: '6',
      win: '2',
      draw: '0',
      lose: '4',
      for: '14',
      against: '21',
      goal_difference: '-7',
      points: '6'
    },
    {
      _id: 'Clacton 1',
      division: '3se',
      played: '6',
      win: '1',
      draw: '1',
      lose: '4',
      for: '10',
      against: '21',
      goal_difference: '-11',
      points: '4'
    },
    {
      _id: 'East London 3',
      division: '3se',
      played: '6',
      win: '1',
      draw: '0',
      lose: '5',
      for: '11',
      against: '20',
      goal_difference: '-9',
      points: '3'
    },
    {
      _id: 'Crostyx 2',
      division: '3se',
      played: '6',
      win: '1',
      draw: '0',
      lose: '5',
      for: '6',
      against: '22',
      goal_difference: '-16',
      points: '3'
    },
    {
      _id: 'Brentwood 2',
      division: '3se',
      played: '6',
      win: '1',
      draw: '0',
      lose: '5',
      for: '12',
      against: '29',
      goal_difference: '-17',
      points: '3'
    },
    {
      _id: 'Saffron Walden 3',
      division: '4se',
      played: '6',
      win: '5',
      draw: '1',
      lose: '0',
      for: '30',
      against: '12',
      goal_difference: '18',
      points: '16'
    },
    {
      _id: 'Plashet 1',
      division: '4se',
      played: '6',
      win: '5',
      draw: '0',
      lose: '1',
      for: '35',
      against: '10',
      goal_difference: '25',
      points: '15'
    },
    {
      _id: 'Chelmsford 3',
      division: '4se',
      played: '6',
      win: '5',
      draw: '0',
      lose: '1',
      for: '19',
      against: '8',
      goal_difference: '11',
      points: '15'
    },
    {
      _id: 'Waltham Forest 2',
      division: '4se',
      played: '6',
      win: '4',
      draw: '0',
      lose: '2',
      for: '18',
      against: '10',
      goal_difference: '8',
      points: '12'
    },
    {
      _id: 'Wapping 7',
      division: '4se',
      played: '6',
      win: '4',
      draw: '0',
      lose: '2',
      for: '13',
      against: '8',
      goal_difference: '5',
      points: '12'
    },
    {
      _id: 'East London 4',
      division: '4se',
      played: '6',
      win: '3',
      draw: '0',
      lose: '3',
      for: '11',
      against: '10',
      goal_difference: '1',
      points: '9'
    },
    {
      _id: 'Witham 2',
      division: '4se',
      played: '6',
      win: '2',
      draw: '2',
      lose: '2',
      for: '17',
      against: '15',
      goal_difference: '2',
      points: '8'
    },
    {
      _id: 'Old Southendian 2',
      division: '4se',
      played: '6',
      win: '2',
      draw: '1',
      lose: '3',
      for: '11',
      against: '23',
      goal_difference: '-12',
      points: '7'
    },
    {
      _id: 'Romford 1',
      division: '4se',
      played: '6',
      win: '1',
      draw: '1',
      lose: '4',
      for: '13',
      against: '22',
      goal_difference: '-9',
      points: '4'
    },
    {
      _id: 'Brentwood 3',
      division: '4se',
      played: '6',
      win: '1',
      draw: '1',
      lose: '4',
      for: '6',
      against: '25',
      goal_difference: '-19',
      points: '4'
    },
    {
      _id: 'Havering 2',
      division: '4se',
      played: '6',
      win: '1',
      draw: '0',
      lose: '5',
      for: '8',
      against: '22',
      goal_difference: '-14',
      points: '3'
    },
    {
      _id: 'Colchester 2',
      division: '4se',
      played: '6',
      win: '0',
      draw: '0',
      lose: '6',
      for: '7',
      against: '23',
      goal_difference: '-16',
      points: '0'
    },
    {
      _id: 'Thurrock 1',
      division: '5se',
      played: '6',
      win: '6',
      draw: '0',
      lose: '0',
      for: '25',
      against: '5',
      goal_difference: '20',
      points: '18'
    },
    {
      _id: 'Rochford 1',
      division: '5se',
      played: '6',
      win: '5',
      draw: '0',
      lose: '1',
      for: '22',
      against: '10',
      goal_difference: '12',
      points: '15'
    },
    {
      _id: 'Crostyx 3',
      division: '5se',
      played: '6',
      win: '3',
      draw: '1',
      lose: '2',
      for: '23',
      against: '7',
      goal_difference: '16',
      points: '10'
    },
    {
      _id: 'Wapping 8',
      division: '5se',
      played: '6',
      win: '3',
      draw: '1',
      lose: '2',
      for: '13',
      against: '10',
      goal_difference: '3',
      points: '10'
    },
    {
      _id: 'Upminster 3',
      division: '5se',
      played: '6',
      win: '2',
      draw: '3',
      lose: '1',
      for: '12',
      against: '10',
      goal_difference: '2',
      points: '9'
    },
    {
      _id: 'Southend 2',
      division: '5se',
      played: '6',
      win: '2',
      draw: '2',
      lose: '2',
      for: '16',
      against: '16',
      goal_difference: '0',
      points: '8'
    },
    {
      _id: 'Redbridge & Ilford 2',
      division: '5se',
      played: '6',
      win: '2',
      draw: '1',
      lose: '3',
      for: '16',
      against: '16',
      goal_difference: '0',
      points: '7'
    },
    {
      _id: 'Waltham Forest 3',
      division: '5se',
      played: '6',
      win: '2',
      draw: '1',
      lose: '3',
      for: '14',
      against: '16',
      goal_difference: '-2',
      points: '7'
    },
    {
      _id: 'East London 5',
      division: '5se',
      played: '6',
      win: '2',
      draw: '1',
      lose: '3',
      for: '11',
      against: '16',
      goal_difference: '-5',
      points: '7'
    },
    {
      _id: 'Witham 3',
      division: '5se',
      played: '6',
      win: '2',
      draw: '0',
      lose: '4',
      for: '9',
      against: '19',
      goal_difference: '-10',
      points: '6'
    },
    {
      _id: 'Old Southendian 3',
      division: '5se',
      played: '6',
      win: '1',
      draw: '2',
      lose: '3',
      for: '8',
      against: '17',
      goal_difference: '-9',
      points: '5'
    },
    {
      _id: 'Clacton 2',
      division: '5se',
      played: '6',
      win: '0',
      draw: '0',
      lose: '6',
      for: '2',
      against: '29',
      goal_difference: '-27',
      points: '0'
    },
    {
      _id: 'Old Loughts Academy',
      division: '6se',
      played: '6',
      win: '6',
      draw: '0',
      lose: '0',
      for: '32',
      against: '8',
      goal_difference: '24',
      points: '18'
    },
    {
      _id: 'Chelmsford 4',
      division: '6se',
      played: '6',
      win: '4',
      draw: '1',
      lose: '1',
      for: '27',
      against: '13',
      goal_difference: '14',
      points: '13'
    },
    {
      _id: 'East London 7',
      division: '6se',
      played: '6',
      win: '4',
      draw: '0',
      lose: '2',
      for: '28',
      against: '9',
      goal_difference: '19',
      points: '12'
    },
    {
      _id: 'East London 6',
      division: '6se',
      played: '6',
      win: '3',
      draw: '1',
      lose: '2',
      for: '18',
      against: '8',
      goal_difference: '10',
      points: '10'
    },
    {
      _id: 'Saffron Walden 4',
      division: '6se',
      played: '6',
      win: '3',
      draw: '1',
      lose: '2',
      for: '17',
      against: '11',
      goal_difference: '6',
      points: '10'
    },
    {
      _id: 'Wapping 9',
      division: '6se',
      played: '6',
      win: '3',
      draw: '0',
      lose: '3',
      for: '13',
      against: '18',
      goal_difference: '-5',
      points: '9'
    },
    {
      _id: 'Braintree 2',
      division: '6se',
      played: '6',
      win: '2',
      draw: '1',
      lose: '3',
      for: '10',
      against: '14',
      goal_difference: '-4',
      points: '7'
    },
    {
      _id: 'Chelmsford 5',
      division: '6se',
      played: '6',
      win: '2',
      draw: '0',
      lose: '4',
      for: '15',
      against: '18',
      goal_difference: '-3',
      points: '6'
    },
    {
      _id: 'Basildon 1',
      division: '6se',
      played: '6',
      win: '2',
      draw: '0',
      lose: '4',
      for: '8',
      against: '29',
      goal_difference: '-21',
      points: '6'
    },
    {
      _id: 'Colchester 3',
      division: '6se',
      played: '6',
      win: '1',
      draw: '2',
      lose: '3',
      for: '14',
      against: '25',
      goal_difference: '-11',
      points: '5'
    },
    {
      _id: 'Maldon 2',
      division: '6se',
      played: '6',
      win: '1',
      draw: '1',
      lose: '4',
      for: '13',
      against: '26',
      goal_difference: '-13',
      points: '4'
    },
    {
      _id: 'Brentwood 4',
      division: '6se',
      played: '6',
      win: '1',
      draw: '1',
      lose: '4',
      for: '11',
      against: '27',
      goal_difference: '-16',
      points: '4'
    },
    {
      _id: 'Old Loughts Loppers',
      division: '7se',
      played: '6',
      win: '5',
      draw: '1',
      lose: '0',
      for: '32',
      against: '7',
      goal_difference: '25',
      points: '16'
    },
    {
      _id: 'Saffron Walden 5',
      division: '7se',
      played: '6',
      win: '5',
      draw: '1',
      lose: '0',
      for: '23',
      against: '9',
      goal_difference: '14',
      points: '16'
    },
    {
      _id: 'Havering 3',
      division: '7se',
      played: '6',
      win: '4',
      draw: '1',
      lose: '1',
      for: '33',
      against: '7',
      goal_difference: '26',
      points: '13'
    },
    {
      _id: 'Upminster 4',
      division: '7se',
      played: '6',
      win: '3',
      draw: '2',
      lose: '1',
      for: '16',
      against: '10',
      goal_difference: '6',
      points: '11'
    },
    {
      _id: 'Witham 4',
      division: '7se',
      played: '6',
      win: '3',
      draw: '0',
      lose: '3',
      for: '13',
      against: '19',
      goal_difference: '-6',
      points: '9'
    },
    {
      _id: 'Redbridge & Ilford 3',
      division: '7se',
      played: '6',
      win: '2',
      draw: '2',
      lose: '2',
      for: '9',
      against: '9',
      goal_difference: '0',
      points: '8'
    },
    {
      _id: 'Chelmsford 6',
      division: '7se',
      played: '6',
      win: '2',
      draw: '1',
      lose: '3',
      for: '14',
      against: '16',
      goal_difference: '-2',
      points: '7'
    },
    {
      _id: 'Saffron Walden 6',
      division: '7se',
      played: '6',
      win: '2',
      draw: '1',
      lose: '3',
      for: '11',
      against: '15',
      goal_difference: '-4',
      points: '7'
    },
    {
      _id: 'Witham Academy',
      division: '7se',
      played: '6',
      win: '2',
      draw: '1',
      lose: '3',
      for: '12',
      against: '21',
      goal_difference: '-9',
      points: '7'
    },
    {
      _id: 'Braintree 3',
      division: '7se',
      played: '6',
      win: '1',
      draw: '1',
      lose: '4',
      for: '16',
      against: '23',
      goal_difference: '-7',
      points: '4'
    },
    {
      _id: 'Wapping X',
      division: '7se',
      played: '6',
      win: '1',
      draw: '1',
      lose: '4',
      for: '9',
      against: '20',
      goal_difference: '-11',
      points: '4'
    },
    {
      _id: 'Waltham Forest 4',
      division: '7se',
      played: '6',
      win: '0',
      draw: '0',
      lose: '6',
      for: '5',
      against: '37',
      goal_difference: '-32',
      points: '0'
    },
    {
      _id: 'Tower Hamlets 1',
      division: '8se',
      played: '6',
      win: '6',
      draw: '0',
      lose: '0',
      for: '41',
      against: '2',
      goal_difference: '39',
      points: '18'
    },
    {
      _id: 'Romford 2',
      division: '8se',
      played: '6',
      win: '5',
      draw: '0',
      lose: '1',
      for: '22',
      against: '7',
      goal_difference: '15',
      points: '15'
    },
    {
      _id: 'Wapping XI',
      division: '8se',
      played: '6',
      win: '4',
      draw: '1',
      lose: '1',
      for: '18',
      against: '9',
      goal_difference: '9',
      points: '13'
    },
    {
      _id: 'Old Southendian 4',
      division: '8se',
      played: '6',
      win: '3',
      draw: '2',
      lose: '1',
      for: '16',
      against: '8',
      goal_difference: '8',
      points: '11'
    },
    {
      _id: 'Brentwood Academy',
      division: '8se',
      played: '6',
      win: '2',
      draw: '2',
      lose: '2',
      for: '8',
      against: '14',
      goal_difference: '-6',
      points: '8'
    },
    {
      _id: 'East London 8',
      division: '8se',
      played: '6',
      win: '2',
      draw: '1',
      lose: '3',
      for: '10',
      against: '5',
      goal_difference: '5',
      points: '7'
    },
    {
      _id: 'Braintree Knights',
      division: '8se',
      played: '6',
      win: '2',
      draw: '1',
      lose: '3',
      for: '16',
      against: '16',
      goal_difference: '0',
      points: '7'
    },
    {
      _id: 'Colchester 4',
      division: '8se',
      played: '6',
      win: '2',
      draw: '0',
      lose: '4',
      for: '10',
      against: '21',
      goal_difference: '-11',
      points: '6'
    },
    {
      _id: 'Saffron Walden 7',
      division: '8se',
      played: '6',
      win: '1',
      draw: '2',
      lose: '3',
      for: '9',
      against: '22',
      goal_difference: '-13',
      points: '5'
    },
    {
      _id: 'Thurrock 2',
      division: '8se',
      played: '6',
      win: '1',
      draw: '1',
      lose: '4',
      for: '8',
      against: '27',
      goal_difference: '-19',
      points: '4'
    },
    {
      _id: 'Old Southendian 5',
      division: '8se',
      played: '6',
      win: '2',
      draw: '0',
      lose: '4',
      for: '5',
      against: '17',
      goal_difference: '-12',
      points: '3'
    },
    {
      _id: 'Brentwood 5',
      division: '8se',
      played: '6',
      win: '0',
      draw: '2',
      lose: '4',
      for: '8',
      against: '23',
      goal_difference: '-15',
      points: '2'
    },
    {
      _id: 'Old Loughts Willows 1',
      division: '9se',
      played: '6',
      win: '5',
      draw: '1',
      lose: '0',
      for: '31',
      against: '4',
      goal_difference: '27',
      points: '16'
    },
    {
      _id: 'Upminster 5',
      division: '9se',
      played: '6',
      win: '4',
      draw: '0',
      lose: '2',
      for: '18',
      against: '18',
      goal_difference: '0',
      points: '12'
    },
    {
      _id: 'Southend 3',
      division: '9se',
      played: '6',
      win: '3',
      draw: '2',
      lose: '1',
      for: '17',
      against: '17',
      goal_difference: '0',
      points: '11'
    },
    {
      _id: 'Crostyx 4',
      division: '9se',
      played: '6',
      win: '3',
      draw: '0',
      lose: '3',
      for: '16',
      against: '15',
      goal_difference: '1',
      points: '9'
    },
    {
      _id: 'Havering 4',
      division: '9se',
      played: '6',
      win: '2',
      draw: '2',
      lose: '2',
      for: '10',
      against: '11',
      goal_difference: '-1',
      points: '8'
    },
    {
      _id: 'Maldon Academy',
      division: '9se',
      played: '6',
      win: '1',
      draw: '2',
      lose: '3',
      for: '9',
      against: '18',
      goal_difference: '-9',
      points: '5'
    },
    {
      _id: 'Rochford 2',
      division: '9se',
      played: '6',
      win: '1',
      draw: '1',
      lose: '4',
      for: '9',
      against: '19',
      goal_difference: '-10',
      points: '4'
    },
    {
      _id: 'London Royals 1',
      division: '9se',
      played: '6',
      win: '1',
      draw: '0',
      lose: '5',
      for: '9',
      against: '17',
      goal_difference: '-8',
      points: '3'
    },
    {
      _id: 'Braintree 5',
      division: '10se',
      played: '6',
      win: '4',
      draw: '2',
      lose: '0',
      for: '24',
      against: '6',
      goal_difference: '18',
      points: '14'
    },
    {
      _id: 'Old Loughts Willows 2',
      division: '10se',
      played: '6',
      win: '3',
      draw: '2',
      lose: '1',
      for: '10',
      against: '4',
      goal_difference: '6',
      points: '11'
    },
    {
      _id: 'East London 9',
      division: '10se',
      played: '6',
      win: '3',
      draw: '1',
      lose: '2',
      for: '11',
      against: '10',
      goal_difference: '1',
      points: '10'
    },
    {
      _id: 'Chelmsford 7',
      division: '10se',
      played: '6',
      win: '2',
      draw: '3',
      lose: '1',
      for: '12',
      against: '5',
      goal_difference: '7',
      points: '9'
    },
    {
      _id: 'Romford 3',
      division: '10se',
      played: '6',
      win: '3',
      draw: '0',
      lose: '3',
      for: '19',
      against: '17',
      goal_difference: '2',
      points: '9'
    },
    {
      _id: 'Old Southendian 6',
      division: '10se',
      played: '6',
      win: '3',
      draw: '0',
      lose: '3',
      for: '14',
      against: '13',
      goal_difference: '1',
      points: '9'
    },
    {
      _id: 'Saffron Walden 8',
      division: '10se',
      played: '6',
      win: '1',
      draw: '0',
      lose: '5',
      for: '7',
      against: '20',
      goal_difference: '-13',
      points: '3'
    },
    {
      _id: 'Waltham Forest 5',
      division: '10se',
      played: '6',
      win: '0',
      draw: '2',
      lose: '4',
      for: '3',
      against: '25',
      goal_difference: '-22',
      points: '2'
    }
  ]
}
