version: 0.2

phases:
  build:
    commands:
    - npm install
    - npm run lint
    - npm run test
    - npm run build
    - mkdir target
    - mv ./dist ./target/dist
    - ls -lart ./target
artifacts:
  files:
    - target/dist/**/*
